# Generated by @typespec/hello-python-emitter [string renderer]. Do not edit by hand.

from typing import Any


def to_dict(value: Any) -> dict:
    """Best-effort serialization helper (string renderer placeholder)."""
    if hasattr(value, '__dict__'):
        return dict(value.__dict__)
    return dict(value)
