# Generated by @typespec/hello-python-emitter [alloy renderer]. Do not edit by hand.

from __future__ import annotations

import datetime
import decimal
from typing import Any, ClassVar, Dict, List, Mapping, Optional

from .._vendor import _from_dict, _parse_datetime, _to_dict
from ._enums import OperationState


class FakedSharedModel:
    """Faked shared model."""

    tag: str
    created_at: datetime.datetime

    _SERIALIZED_NAMES: ClassVar[Dict[str, str]] = {
        "tag": "tag",
        "created_at": "createdAt",
    }

    def __init__(
        self,
        *,
        tag: str,
        created_at: datetime.datetime,
    ) -> None:
        self.tag = tag
        self.created_at = created_at

    def as_dict(self) -> Dict[str, Any]:
        d: Dict[str, Any] = {}
        if self.tag is not None:
            d["tag"] = _to_dict(self.tag)
        if self.created_at is not None:
            d["createdAt"] = _to_dict(self.created_at)
        return d

    @classmethod
    def from_dict(cls, data: Mapping[str, Any]) -> "FakedSharedModel":
        return cls(
            tag=data.get("tag"),
            created_at=_parse_datetime(data.get("createdAt")),
        )

class WidgetSuite:
    """A widget."""

    name: str
    manufacturer_id: str
    shared_model: Optional[FakedSharedModel] = None

    _SERIALIZED_NAMES: ClassVar[Dict[str, str]] = {
        "name": "name",
        "manufacturer_id": "manufacturerId",
        "shared_model": "sharedModel",
    }

    def __init__(
        self,
        *,
        name: str,
        manufacturer_id: str,
        shared_model: Optional[FakedSharedModel] = None,
    ) -> None:
        self.name = name
        self.manufacturer_id = manufacturer_id
        self.shared_model = shared_model

    def as_dict(self) -> Dict[str, Any]:
        d: Dict[str, Any] = {}
        if self.name is not None:
            d["name"] = _to_dict(self.name)
        if self.manufacturer_id is not None:
            d["manufacturerId"] = _to_dict(self.manufacturer_id)
        if self.shared_model is not None:
            d["sharedModel"] = _to_dict(self.shared_model)
        return d

    @classmethod
    def from_dict(cls, data: Mapping[str, Any]) -> "WidgetSuite":
        return cls(
            name=data.get("name"),
            manufacturer_id=data.get("manufacturerId"),
            shared_model=_from_dict(FakedSharedModel, data.get("sharedModel")),
        )

class InnerError:
    """An object containing more specific information about the error. As per Azure REST API guidelines - https://aka.ms/AzureRestApiGuidelines#handling-errors."""

    code: Optional[str] = None
    innererror: Optional[InnerError] = None

    _SERIALIZED_NAMES: ClassVar[Dict[str, str]] = {
        "code": "code",
        "innererror": "innererror",
    }

    def __init__(
        self,
        *,
        code: Optional[str] = None,
        innererror: Optional[InnerError] = None,
    ) -> None:
        self.code = code
        self.innererror = innererror

    def as_dict(self) -> Dict[str, Any]:
        d: Dict[str, Any] = {}
        if self.code is not None:
            d["code"] = _to_dict(self.code)
        if self.innererror is not None:
            d["innererror"] = _to_dict(self.innererror)
        return d

    @classmethod
    def from_dict(cls, data: Mapping[str, Any]) -> "InnerError":
        return cls(
            code=data.get("code"),
            innererror=_from_dict(InnerError, data.get("innererror")),
        )

class Error:
    """The error object."""

    code: str
    message: str
    target: Optional[str] = None
    details: Optional[list[Error]] = None
    innererror: Optional[InnerError] = None

    _SERIALIZED_NAMES: ClassVar[Dict[str, str]] = {
        "code": "code",
        "message": "message",
        "target": "target",
        "details": "details",
        "innererror": "innererror",
    }

    def __init__(
        self,
        *,
        code: str,
        message: str,
        target: Optional[str] = None,
        details: Optional[list[Error]] = None,
        innererror: Optional[InnerError] = None,
    ) -> None:
        self.code = code
        self.message = message
        self.target = target
        self.details = details
        self.innererror = innererror

    def as_dict(self) -> Dict[str, Any]:
        d: Dict[str, Any] = {}
        if self.code is not None:
            d["code"] = _to_dict(self.code)
        if self.message is not None:
            d["message"] = _to_dict(self.message)
        if self.target is not None:
            d["target"] = _to_dict(self.target)
        if self.details is not None:
            d["details"] = _to_dict(self.details)
        if self.innererror is not None:
            d["innererror"] = _to_dict(self.innererror)
        return d

    @classmethod
    def from_dict(cls, data: Mapping[str, Any]) -> "Error":
        return cls(
            code=data.get("code"),
            message=data.get("message"),
            target=data.get("target"),
            details=[_from_dict(Error, v) for v in (data.get("details") or [])],
            innererror=_from_dict(InnerError, data.get("innererror")),
        )

class ResourceOperationStatus:
    """Provides status details for long running operations."""

    id: str
    status: OperationState
    error: Optional[Error] = None
    result: Optional[WidgetSuite] = None

    _SERIALIZED_NAMES: ClassVar[Dict[str, str]] = {
        "id": "id",
        "status": "status",
        "error": "error",
        "result": "result",
    }

    def __init__(
        self,
        *,
        id: str,
        status: OperationState,
        error: Optional[Error] = None,
        result: Optional[WidgetSuite] = None,
    ) -> None:
        self.id = id
        self.status = status
        self.error = error
        self.result = result

    def as_dict(self) -> Dict[str, Any]:
        d: Dict[str, Any] = {}
        if self.id is not None:
            d["id"] = _to_dict(self.id)
        if self.status is not None:
            d["status"] = _to_dict(self.status)
        if self.error is not None:
            d["error"] = _to_dict(self.error)
        if self.result is not None:
            d["result"] = _to_dict(self.result)
        return d

    @classmethod
    def from_dict(cls, data: Mapping[str, Any]) -> "ResourceOperationStatus":
        return cls(
            id=data.get("id"),
            status=_from_dict(OperationState, data.get("status")),
            error=_from_dict(Error, data.get("error")),
            result=_from_dict(WidgetSuite, data.get("result")),
        )

class OperationStatus:
    """Provides status details for long running operations."""

    id: str
    status: OperationState
    error: Optional[Error] = None
    result: Optional[None] = None

    _SERIALIZED_NAMES: ClassVar[Dict[str, str]] = {
        "id": "id",
        "status": "status",
        "error": "error",
        "result": "result",
    }

    def __init__(
        self,
        *,
        id: str,
        status: OperationState,
        error: Optional[Error] = None,
        result: Optional[None] = None,
    ) -> None:
        self.id = id
        self.status = status
        self.error = error
        self.result = result

    def as_dict(self) -> Dict[str, Any]:
        d: Dict[str, Any] = {}
        if self.id is not None:
            d["id"] = _to_dict(self.id)
        if self.status is not None:
            d["status"] = _to_dict(self.status)
        if self.error is not None:
            d["error"] = _to_dict(self.error)
        if self.result is not None:
            d["result"] = _to_dict(self.result)
        return d

    @classmethod
    def from_dict(cls, data: Mapping[str, Any]) -> "OperationStatus":
        return cls(
            id=data.get("id"),
            status=_from_dict(OperationState, data.get("status")),
            error=_from_dict(Error, data.get("error")),
            result=_from_dict(None, data.get("result")),
        )

class CustomPage:
    """Paged collection of WidgetSuite items."""

    value: list[WidgetSuite]
    next_link: Optional[Any] = None

    _SERIALIZED_NAMES: ClassVar[Dict[str, str]] = {
        "value": "value",
        "next_link": "nextLink",
    }

    def __init__(
        self,
        *,
        value: list[WidgetSuite],
        next_link: Optional[Any] = None,
    ) -> None:
        self.value = value
        self.next_link = next_link

    def as_dict(self) -> Dict[str, Any]:
        d: Dict[str, Any] = {}
        if self.value is not None:
            d["value"] = _to_dict(self.value)
        if self.next_link is not None:
            d["nextLink"] = _to_dict(self.next_link)
        return d

    @classmethod
    def from_dict(cls, data: Mapping[str, Any]) -> "CustomPage":
        return cls(
            value=[_from_dict(WidgetSuite, v) for v in (data.get("value") or [])],
            next_link=data.get("nextLink"),
        )
