# Generated by @typespec/hello-python-emitter [template renderer]. Do not edit by hand.
from .operations._operations import (
    list,
    get,
    create,
    delete,
    ping,
)


class HelloServiceClient:
    """Synthetic top-level client (template renderer)."""

    def __init__(self, endpoint: str) -> None:
        self._endpoint = endpoint

    def list(self) -> WidgetList:
        return list()

    def get(self, id: str) -> Widget:
        return get(id)

    def create(self, widget: Widget) -> Widget:
        return create(widget)

    def delete(self, id: str) -> None:
        return delete(id)

    def ping(self) -> str:
        return ping()

