# Generated by @typespec/hello-python-emitter [ef-mix renderer]. Do not edit by
# hand.

from dataclasses import dataclass
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from typing import Optional


@dataclass(kw_only=True)
class Widget:
    id: str
    name: str
    weight: int
    color: Optional[str] = None


@dataclass(kw_only=True)
class WidgetList:
    items: list[Widget]
    next_link: Optional[str] = None
