# Generated by @typespec/hello-python-emitter [ef-mix renderer]. Do not edit by
# hand.

from typing import Any


def to_dict(value: Any) -> dict:
    """Best-effort serialization helper (ef-mix renderer placeholder)."""
    if hasattr(value, "__dict__"):
        return dict(value.__dict__)
    return dict(value)
