# Generated by @typespec/hello-python-emitter [template renderer]. Do not edit by hand.

from ._client import WidgetAnalyticsClient
from ._version import VERSION as __version__

__all__ = ["WidgetAnalyticsClient", "__version__"]
