# Generated by @typespec/hello-python-emitter [alloy renderer]. Do not edit by
# hand.

from typing import Any


def to_dict(value: Any) -> dict:
    """Best-effort serialization helper (alloy renderer placeholder)."""
    if hasattr(value, "__dict__"):
        return dict(value.__dict__)
    return dict(value)
