# Generated by @typespec/hello-python-emitter [template renderer]. Do not edit by hand.
from dataclasses import dataclass
from typing import Any, Optional


@dataclass
class Widget:
    id: str
    name: str
    weight: int
    color: Optional[str] = None


@dataclass
class WidgetList:
    items: list[Widget]
    next_link: Optional[str] = None

