# Generated by @typespec/hello-python-emitter [string renderer]. Do not edit by hand.

from enum import Enum


class OperationState(str, Enum):
    """Enum describing allowed operation states."""
    NOT_STARTED = "NotStarted"
    RUNNING = "Running"
    SUCCEEDED = "Succeeded"
    FAILED = "Failed"
    CANCELED = "Canceled"
