# Generated by @typespec/hello-python-emitter [string renderer]. Do not edit by hand.

from typing import Any

def list() -> WidgetList:
    """Stub implementation of `list` (string renderer)."""
    raise NotImplementedError("Operation 'list' is not implemented yet")

def get(id: str) -> Widget:
    """Stub implementation of `get` (string renderer)."""
    raise NotImplementedError("Operation 'get' is not implemented yet")

def create(widget: Widget) -> Widget:
    """Stub implementation of `create` (string renderer)."""
    raise NotImplementedError("Operation 'create' is not implemented yet")

def delete(id: str) -> None:
    """Stub implementation of `delete` (string renderer)."""
    raise NotImplementedError("Operation 'delete' is not implemented yet")

def ping() -> str:
    """Stub implementation of `ping` (string renderer)."""
    raise NotImplementedError("Operation 'ping' is not implemented yet")
