# Generated by @typespec/hello-python-emitter [ef-mix renderer]. Do not edit by hand.

from typing import Any, TYPE_CHECKING

from azure.core import PipelineClient
from azure.core.pipeline import policies
from azure.core.rest import HttpRequest, HttpResponse

from ._configuration import WidgetAnalyticsClientConfiguration
from .operations._operations import WidgetAnalyticsOperations

if TYPE_CHECKING:
    from azure.core.credentials import TokenCredential


class WidgetAnalyticsClient:
    """WidgetAnalytics.

    :ivar widget_analytics: WidgetAnalyticsOperations operations
    :vartype widget_analytics: widget_analytics.operations.WidgetAnalyticsOperations
    :param endpoint: Service endpoint URL.
    :type endpoint: str
    :param credential: Credential needed for the client to connect to Azure.
    :type credential: ~azure.core.credentials.TokenCredential
    :keyword api_version: The API version to use. Default value is "2022-12-01".
    :paramtype api_version: str
    """

    def __init__(
        self,
        endpoint: str,
        credential: "TokenCredential",
        *,
        api_version: str = "2022-12-01",
        **kwargs: Any,
    ) -> None:
        self._config = WidgetAnalyticsClientConfiguration(
            endpoint=endpoint,
            credential=credential,
            api_version=api_version,
            **kwargs,
        )
        _policies = kwargs.pop("policies", None)
        if _policies is None:
            _policies = [
                policies.RequestIdPolicy(**kwargs),
                self._config.headers_policy,
                self._config.user_agent_policy,
                self._config.proxy_policy,
                policies.ContentDecodePolicy(**kwargs),
                self._config.redirect_policy,
                self._config.retry_policy,
                self._config.authentication_policy,
                self._config.custom_hook_policy,
                self._config.logging_policy,
            ]
        self._client: PipelineClient = PipelineClient(base_url=endpoint, policies=_policies, **kwargs)
        self.widget_analytics = WidgetAnalyticsOperations(self._client, self._config)

    def send_request(
        self,
        request: HttpRequest,
        *,
        stream: bool = False,
        **kwargs: Any,
    ) -> HttpResponse:
        """Run the network request through the client's chained policies."""
        return self._client.send_request(request, stream=stream, **kwargs)  # type: ignore

    def close(self) -> None:
        self._client.close()

    def __enter__(self) -> "WidgetAnalyticsClient":
        self._client.__enter__()
        return self

    def __exit__(self, *exc_details: Any) -> None:
        self._client.__exit__(*exc_details)
