# Generated by @typespec/hello-python-emitter [ef-mix renderer]. Do not edit by
# hand.

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from models._models import Widget
    from models._models import WidgetList


def list() -> WidgetList:
    raise NotImplementedError("Operation 'list' is not implemented yet")


def get(id: str) -> Widget:
    raise NotImplementedError("Operation 'get' is not implemented yet")


def create(widget: Widget) -> Widget:
    raise NotImplementedError("Operation 'create' is not implemented yet")


def delete(id: str) -> None:
    raise NotImplementedError("Operation 'delete' is not implemented yet")


def ping() -> str:
    raise NotImplementedError("Operation 'ping' is not implemented yet")
