# Generated by @typespec/hello-python-emitter [ef-mix renderer]. Do not edit by hand.

from typing import Any, Optional

from azure.core.exceptions import HttpResponseError
from azure.core.paging import ItemPaged
from azure.core.polling import LROPoller
from azure.core.polling.base_polling import LROBasePolling
from azure.core.rest import HttpRequest

from .._vendor import _api_version_query, _from_dict, _to_dict
from ..models._models import FakedSharedModel, WidgetSuite, InnerError, Error, ResourceOperationStatus, OperationStatus, CustomPage
from ..models._enums import OperationState


class WidgetAnalyticsOperations:
    """WidgetAnalytics operations."""

    def __init__(self, client, config) -> None:
        self._client = client
        self._config = config

    def get_widget(
        self,
        widget_name: str,
        **kwargs: Any,
    ) -> WidgetSuite:
        """Fetch a Widget by name."""
        _params: dict = {**_api_version_query(self._config)}
        _request = HttpRequest("GET", f"/widgets/{widget_name}", params=_params)
        _response = self._client.send_request(_request, **kwargs)
        if _response.status_code not in (200,):
            raise HttpResponseError(response=_response)
        _payload = _response.json() if _response.content else None
        return _from_dict(WidgetSuite, _payload)  # type: ignore[return-value]

    def get_widget_operation_status(
        self,
        widget_name: str,
        operation_id: str,
        **kwargs: Any,
    ) -> ResourceOperationStatus:
        """Gets status of a Widget operation."""
        _params: dict = {**_api_version_query(self._config)}
        _request = HttpRequest("GET", f"/widgets/{widget_name}/operations/{operation_id}", params=_params)
        _response = self._client.send_request(_request, **kwargs)
        if _response.status_code not in (200,):
            raise HttpResponseError(response=_response)
        _payload = _response.json() if _response.content else None
        return _from_dict(ResourceOperationStatus, _payload)  # type: ignore[return-value]

    def begin_create_or_update_widget(
        self,
        widget_name: str,
        resource: WidgetSuite,
        **kwargs: Any,
    ) -> LROPoller[WidgetSuite]:
        """Creates or updates a Widget asynchronously."""
        _params: dict = {**_api_version_query(self._config)}
        _headers: dict = {"Content-Type": "application/merge-patch+json"}
        _headers = {k: v for k, v in _headers.items() if v is not None}
        _body = _to_dict(resource)
        _request = HttpRequest("PATCH", f"/widgets/{widget_name}", params=_params, headers=_headers, json=_body)
        _initial = self._client.send_request(_request, **kwargs)
        if _initial.status_code not in (201,):
            raise HttpResponseError(response=_initial)
        _polling = LROBasePolling(lro_options={"final-state-via": "azure-async-operation"}, **kwargs)
        def _deserialize(pipeline_response):
            payload = pipeline_response.http_response.json() if pipeline_response.http_response.content else None
            return _from_dict(WidgetSuite, payload)
        return LROPoller(self._client, _initial, _deserialize, _polling)

    def begin_delete_widget(
        self,
        widget_name: str,
        **kwargs: Any,
    ) -> LROPoller[None]:
        """Delete a Widget asynchronously."""
        _params: dict = {**_api_version_query(self._config)}
        _request = HttpRequest("DELETE", f"/widgets/{widget_name}", params=_params)
        _initial = self._client.send_request(_request, **kwargs)
        if _initial.status_code not in (202,):
            raise HttpResponseError(response=_initial)
        _polling = LROBasePolling(lro_options={"final-state-via": "azure-async-operation"}, **kwargs)
        def _deserialize(pipeline_response):
            return None
        return LROPoller(self._client, _initial, _deserialize, _polling)

    def list_widgets(
        self,
        **kwargs: Any,
    ) -> ItemPaged[WidgetSuite]:
        """List Widget resources."""
        _params: dict = {**_api_version_query(self._config)}
        def _prepare(next_link: Optional[str] = None) -> HttpRequest:
            if next_link is None:
                return HttpRequest("GET", "/widgets", params=_params)
            return HttpRequest("GET", next_link)

        def _extract(pipeline_response):
            payload = pipeline_response.http_response.json()
            items = [_from_dict(WidgetSuite, v) for v in payload.get("value", [])]
            return payload.get("nextLink"), iter(items)

        def _get_next(next_link: Optional[str] = None):
            request = _prepare(next_link)
            return self._client._pipeline.run(request, stream=False, **kwargs)

        return ItemPaged(_get_next, _extract)
