# Generated by @typespec/hello-python-emitter [alloy renderer]. Do not edit by
# hand.

from dataclasses import dataclass


@dataclass
class Widget:
    id: str
    name: str
    weight: int
    color: str | None = None


@dataclass
class WidgetList:
    items: list[Widget]
    next_link: str | None = None
