# Generated by @typespec/hello-python-emitter [string renderer]. Do not edit by hand.

from typing import Any, TYPE_CHECKING

from azure.core.pipeline import policies

from ._version import VERSION

if TYPE_CHECKING:
    from azure.core.credentials import TokenCredential


class WidgetAnalyticsClientConfiguration:
    """Configuration for WidgetAnalyticsClient.

    Note that all parameters used to create this instance are saved as instance attributes.
    """

    def __init__(
        self,
        endpoint: str,
        credential: "TokenCredential",
        *,
        api_version: str = "2022-12-01",
        **kwargs: Any,
    ) -> None:
        self.endpoint = endpoint
        self.credential = credential
        self.api_version = api_version
        self.credential_scopes = kwargs.pop("credential_scopes", ["https://azure.com/.default"])
        kwargs.setdefault("sdk_moniker", f"widget-analytics/{VERSION}")
        self._configure(**kwargs)

    def _configure(self, **kwargs: Any) -> None:
        self.user_agent_policy = kwargs.get("user_agent_policy") or policies.UserAgentPolicy(**kwargs)
        self.headers_policy = kwargs.get("headers_policy") or policies.HeadersPolicy(**kwargs)
        self.proxy_policy = kwargs.get("proxy_policy") or policies.ProxyPolicy(**kwargs)
        self.logging_policy = kwargs.get("logging_policy") or policies.NetworkTraceLoggingPolicy(**kwargs)
        self.http_logging_policy = kwargs.get("http_logging_policy") or policies.HttpLoggingPolicy(**kwargs)
        self.custom_hook_policy = kwargs.get("custom_hook_policy") or policies.CustomHookPolicy(**kwargs)
        self.redirect_policy = kwargs.get("redirect_policy") or policies.RedirectPolicy(**kwargs)
        self.retry_policy = kwargs.get("retry_policy") or policies.RetryPolicy(**kwargs)
        self.authentication_policy = kwargs.get("authentication_policy") or policies.BearerTokenCredentialPolicy(
            self.credential, *self.credential_scopes, **kwargs
        )
