# Generated by @typespec/hello-python-emitter [string renderer]. Do not edit by hand.

import datetime
from typing import Any, Mapping, Optional, Type, TypeVar

T = TypeVar('T')


def _api_version_query(config: Any) -> dict:
    """Build the api-version query-string dict from a client configuration."""
    return {"api-version": config.api_version}


def _to_dict(value: Any) -> Any:
    if value is None:
        return None
    if hasattr(value, "as_dict"):
        return value.as_dict()
    if isinstance(value, (list, tuple)):
        return [_to_dict(v) for v in value]
    if isinstance(value, dict):
        return {k: _to_dict(v) for k, v in value.items()}
    if isinstance(value, datetime.datetime):
        return value.isoformat()
    return value


def _from_dict(cls: Type[T], value: Any) -> Optional[T]:
    if value is None:
        return None
    if hasattr(cls, "from_dict"):
        return cls.from_dict(value)  # type: ignore[return-value]
    return value  # type: ignore[return-value]


def _parse_datetime(value: Any) -> Optional[datetime.datetime]:
    if value is None:
        return None
    if isinstance(value, datetime.datetime):
        return value
    if isinstance(value, str):
        return datetime.datetime.fromisoformat(value.replace("Z", "+00:00"))
    return value
