import { SourceDirectory, SourceFile as CoreSourceFile } from "@alloy-js/core";
import * as py from "@alloy-js/python";
import type { EmitContext } from "@typespec/compiler";
import { Output, writeOutput } from "@typespec/emitter-framework";
import type { HelloPythonEmitterOptions } from "../lib.js";
import type { SdkOperation, SdkParameter, SdkShape } from "../sdk-ir.js";
import type { Renderer } from "./types.js";

const HEADER = "Generated by @typespec/hello-python-emitter [alloy renderer]. Do not edit by hand.";

function paramDescriptors(params: SdkParameter[]) {
  return params.map((p) => ({
    name: p.pyName,
    type: p.optional ? `${p.pyType} | None` : p.pyType,
    default: p.optional ? "None" : undefined,
  }));
}

function OperationFunction({ op }: { op: SdkOperation }) {
  return (
    <py.FunctionDeclaration
      name={op.pyName}
      parameters={paramDescriptors(op.parameters)}
      returnType={op.returnType}
    >
      {`raise NotImplementedError("Operation '${op.name}' is not implemented yet")`}
    </py.FunctionDeclaration>
  );
}

function ClientMethod({ op }: { op: SdkOperation }) {
  const callArgs = op.parameters.map((p) => p.pyName).join(", ");
  return (
    <py.MethodDeclaration
      name={op.pyName}
      parameters={paramDescriptors(op.parameters)}
      returnType={op.returnType}
    >
      {`return ${op.pyName}(${callArgs})`}
    </py.MethodDeclaration>
  );
}

function ModelDataclass({ model }: { model: SdkShape["models"][number] }) {
  return (
    <py.DataclassDeclaration name={model.pyName}>
      {model.properties.length === 0
        ? "pass"
        : model.properties.map((p) =>
            p.optional ? (
              <py.VariableDeclaration
                instanceVariable
                name={p.pyName}
                type={`${p.pyType} | None`}
              />
            ) : (
              <py.VariableDeclaration instanceVariable name={p.pyName} type={p.pyType} omitNone />
            ),
          )}
    </py.DataclassDeclaration>
  );
}

function renderTree(shape: SdkShape, program: EmitContext<HelloPythonEmitterOptions>["program"]) {
  const topInit =
    `from ._client import ${shape.clientName}\n` +
    `from ._version import VERSION as __version__\n`;

  const opsInit =
    shape.operations.map((o) => `from ._operations import ${o.pyName}`).join("\n") + "\n";

  const modelsInit =
    shape.models.length === 0
      ? "# (no user-defined models found)\n"
      : shape.models.map((m) => `from ._models import ${m.pyName}`).join("\n") + "\n";

  const utilsInit = `from ._utils import to_dict\n`;

  const versionFile = `VERSION = "${shape.version}"\n`;

  const utilsFile =
    `from typing import Any\n\n\n` +
    `def to_dict(value: Any) -> dict:\n` +
    `    """Best-effort serialization helper (alloy renderer placeholder)."""\n` +
    `    if hasattr(value, "__dict__"):\n` +
    `        return dict(value.__dict__)\n` +
    `    return dict(value)\n`;

  return (
    <Output
      program={program}
      namePolicy={py.createPythonNamePolicy()}
      externals={[py.dataclassesModule, py.abcModule, py.enumModule]}
      printWidth={80}
      tabWidth={4}
    >
      <py.SourceFile path="__init__.py" headerComment={HEADER}>
        {topInit}
      </py.SourceFile>
      <py.SourceFile path="_version.py" headerComment={HEADER}>
        {versionFile}
      </py.SourceFile>
      <py.SourceFile path="_client.py" headerComment={HEADER}>
        {`from .operations._operations import (\n` +
          shape.operations.map((o) => `    ${o.pyName},\n`).join("") +
          `)\n\n\n`}
        <py.ClassDeclaration name={shape.clientName}>
          <py.DunderMethodDeclaration
            name="__init__"
            parameters={[{ name: "endpoint", type: "str" }]}
          >
            {`self._endpoint = endpoint`}
          </py.DunderMethodDeclaration>
          {shape.operations.map((op) => (
            <ClientMethod op={op} />
          ))}
        </py.ClassDeclaration>
      </py.SourceFile>
      <CoreSourceFile path="py.typed" filetype="text">
        {""}
      </CoreSourceFile>
      <SourceDirectory path="operations">
        <py.SourceFile path="__init__.py" headerComment={HEADER}>
          {opsInit}
        </py.SourceFile>
        <py.SourceFile path="_operations.py" headerComment={HEADER}>
          {shape.operations.map((op) => (
            <OperationFunction op={op} />
          ))}
        </py.SourceFile>
      </SourceDirectory>
      <SourceDirectory path="models">
        <py.SourceFile path="__init__.py" headerComment={HEADER}>
          {modelsInit}
        </py.SourceFile>
        <py.SourceFile path="_models.py" headerComment={HEADER}>
          {shape.models.length === 0
            ? "# (no user-defined models found)\n"
            : shape.models.map((m) => <ModelDataclass model={m} />)}
        </py.SourceFile>
      </SourceDirectory>
      <SourceDirectory path="utils">
        <py.SourceFile path="__init__.py" headerComment={HEADER}>
          {utilsInit}
        </py.SourceFile>
        <py.SourceFile path="_utils.py" headerComment={HEADER}>
          {utilsFile}
        </py.SourceFile>
      </SourceDirectory>
    </Output>
  );
}

export const alloyRenderer: Renderer = {
  id: "alloy",
  description:
    "Pure @alloy-js/core + @alloy-js/python components. Manual type mapping (no emitter-framework).",
  async emit(context: EmitContext<HelloPythonEmitterOptions>, shape, outputDir) {
    const tree = renderTree(shape, context.program);
    await writeOutput(context.program, tree, outputDir);
  },
};
