import { SourceFile as CoreSourceFile, SourceDirectory } from "@alloy-js/core";
import * as alloyPy from "@alloy-js/python";
import type { EmitContext } from "@typespec/compiler";
import { Output, writeOutput } from "@typespec/emitter-framework";
import type { HelloPythonEmitterOptions } from "../lib.js";
import type { SdkEnum, SdkModel, SdkOperation, SdkProperty, SdkShape } from "../sdk-ir.js";
import { buildPatch, docstring, formatTuple, snake, stripOptional } from "./python-builders.js";
import type { Renderer } from "./types.js";

/* ──────────────────────────────────────────────────────────────────
 * Alloy renderer — uses native `@alloy-js/python` components
 * (ClassDeclaration, MethodDeclaration, FunctionDeclaration, …) for
 * all structural Python constructs. Method bodies remain as string
 * children — the imperative logic (LRO polling, paging closures,
 * dict serialisation) is naturally expressed as text, not as a JSX
 * component tree. Imports are string-based because setting up Alloy
 * external modules for every azure-core symbol would be overkill for
 * a benchmark sandbox.
 * ────────────────────────────────────────────────────────────── */

const RID = "alloy";
const HEADER_TEXT = `Generated by @typespec/hello-python-emitter [${RID} renderer]. Do not edit by hand.`;

/* ═══════════════════════  Helpers  ════════════════════════════════ */

function fmtPath(op: SdkOperation): string {
  if (op.pathParameters.length === 0) return `"${op.path}"`;
  let s = op.path;
  for (const p of op.pathParameters) s = s.replace(`{${p.serializedName}}`, `{${p.pyName}}`);
  return `f"${s}"`;
}

function decodeScalar(t: string, src: string): string {
  if (["str", "bool", "int", "float", "Any", "bytes"].includes(t)) return src;
  if (t === "datetime.datetime") return `_parse_datetime(${src})`;
  if (["datetime.date", "datetime.time", "datetime.timedelta"].includes(t)) return src;
  if (t === "decimal.Decimal") return `decimal.Decimal(${src}) if ${src} is not None else None`;
  return `_from_dict(${t}, ${src})`;
}

function decodeExpr(p: SdkProperty): string {
  const key = `data.get("${p.serializedName}")`;
  const t = p.pyType;
  if (t.startsWith("list["))
    return `[${decodeScalar(t.slice(5, -1), "v")} for v in (${key} or [])]`;
  if (t.startsWith("dict[")) return key;
  return decodeScalar(t, key);
}

type Param = alloyPy.ParameterDescriptor | "*" | "/";

/* ═══════════════════  Model class  ═══════════════════════════════ */

function renderModelClass(m: SdkModel) {
  const req = m.properties.filter((p) => !p.optional);
  const opt = m.properties.filter((p) => p.optional);

  if (m.properties.length === 0) {
    return (
      <alloyPy.ClassDeclaration name={m.pyName}>
        {`"""${docstring(m.docstring ?? m.name)}"""\npass`}
      </alloyPy.ClassDeclaration>
    );
  }

  const preamble = [
    `"""${docstring(m.docstring ?? m.name)}"""`,
    "",
    ...req.map((p) => `${p.pyName}: ${p.pyType}`),
    ...opt.map((p) => `${p.pyName}: Optional[${p.pyType}] = None`),
    "",
    "_SERIALIZED_NAMES: ClassVar[Dict[str, str]] = {",
    ...m.properties.map((p) => `    "${p.pyName}": "${p.serializedName}",`),
    "}",
  ].join("\n");

  const initParams: Param[] = [
    "*",
    ...req.map((p): alloyPy.ParameterDescriptor => ({ name: p.pyName, type: p.pyType })),
    ...opt.map(
      (p): alloyPy.ParameterDescriptor => ({
        name: p.pyName,
        type: `Optional[${p.pyType}]`,
        default: null as any,
      }),
    ),
  ];

  const initBody = m.properties.map((p) => `self.${p.pyName} = ${p.pyName}`).join("\n");

  const asDictBody = [
    "d: Dict[str, Any] = {}",
    ...m.properties.map(
      (p) =>
        `if self.${p.pyName} is not None:\n    d["${p.serializedName}"] = _to_dict(self.${p.pyName})`,
    ),
    "return d",
  ].join("\n");

  const fromDictBody = [
    "return cls(",
    ...m.properties.map((p) => `    ${p.pyName}=${decodeExpr(p)},`),
    ")",
  ].join("\n");

  return (
    <alloyPy.ClassDeclaration name={m.pyName}>
      {preamble + "\n"}

      <alloyPy.DunderMethodDeclaration name="__init__" parameters={initParams} returnType="None">
        {initBody}
      </alloyPy.DunderMethodDeclaration>
      {"\n"}
      <alloyPy.MethodDeclaration name="as_dict" returnType="Dict[str, Any]">
        {asDictBody}
      </alloyPy.MethodDeclaration>
      {"\n"}
      <alloyPy.ClassMethodDeclaration
        name="from_dict"
        parameters={[{ name: "data", type: "Mapping[str, Any]" }]}
        returnType={`"${m.pyName}"`}
      >
        {fromDictBody}
      </alloyPy.ClassMethodDeclaration>
    </alloyPy.ClassDeclaration>
  );
}

/* ═══════════════════  Enum class  ════════════════════════════════ */

function renderEnumClass(e: SdkEnum) {
  const body = [
    `"""${docstring(e.docstring ?? e.name)}"""`,
    ...e.members.map((m) => `${m.pyName} = "${m.value}"`),
  ].join("\n");

  return (
    <alloyPy.ClassDeclaration name={e.pyName} bases={["str", "Enum"]}>
      {body}
    </alloyPy.ClassDeclaration>
  );
}

/* ═══════════════════  Operation method body  ═════════════════════ */

function buildOpBody(op: SdkOperation): string {
  const lines: string[] = [];
  const pathExpr = fmtPath(op);

  const queryParts = ["**_api_version_query(self._config)"];
  for (const p of op.queryParameters) {
    if (p.serializedName === "api-version") continue;
    queryParts.push(`"${p.serializedName}": ${p.pyName}`);
  }

  const headerParts: string[] = [];
  const hasUserCt = op.headerParameters.some(
    (p) => p.serializedName.toLowerCase() === "content-type",
  );
  if (op.bodyParameter) {
    const ct =
      hasUserCt && op.verb === "patch" ? "application/merge-patch+json" : "application/json";
    headerParts.push(`"Content-Type": "${ct}"`);
  }
  for (const p of op.headerParameters) {
    if (p.serializedName.toLowerCase() === "content-type") continue;
    headerParts.push(`"${p.serializedName}": ${p.pyName}`);
  }

  lines.push(`_params: dict = {${queryParts.join(", ")}}`);
  if (op.queryParameters.some((p) => p.serializedName !== "api-version")) {
    lines.push("_params = {k: v for k, v in _params.items() if v is not None}");
  }
  if (headerParts.length) {
    lines.push(`_headers: dict = {${headerParts.join(", ")}}`);
    lines.push("_headers = {k: v for k, v in _headers.items() if v is not None}");
  }
  if (op.bodyParameter) {
    lines.push(`_body = _to_dict(${op.bodyParameter.pyName})`);
  }

  if (op.paged) {
    lines.push("def _prepare(next_link: Optional[str] = None) -> HttpRequest:");
    lines.push("    if next_link is None:");
    lines.push(
      `        return HttpRequest("${op.verb.toUpperCase()}", ${pathExpr}, params=_params${headerParts.length ? ", headers=_headers" : ""})`,
    );
    lines.push('    return HttpRequest("GET", next_link)');
    lines.push("");
    lines.push("def _extract(pipeline_response):");
    lines.push("    payload = pipeline_response.http_response.json()");
    lines.push(
      `    items = [_from_dict(${op.paged.itemPyType}, v) for v in payload.get("${op.paged.itemsPath}", [])]`,
    );
    lines.push(`    return payload.get("${op.paged.nextLinkPath ?? "nextLink"}"), iter(items)`);
    lines.push("");
    lines.push("def _get_next(next_link: Optional[str] = None):");
    lines.push("    request = _prepare(next_link)");
    lines.push("    return self._client._pipeline.run(request, stream=False, **kwargs)");
    lines.push("");
    lines.push("return ItemPaged(_get_next, _extract)");
    return lines.join("\n");
  }

  const extras = ["params=_params"];
  if (headerParts.length) extras.push("headers=_headers");
  if (op.bodyParameter) extras.push("json=_body");
  lines.push(
    `_request = HttpRequest("${op.verb.toUpperCase()}", ${pathExpr}, ${extras.join(", ")})`,
  );

  if (op.lro) {
    const expected = op.successStatusCodes.length ? op.successStatusCodes : [200, 201, 202, 204];
    lines.push("_initial = self._client.send_request(_request, **kwargs)");
    lines.push(`if _initial.status_code not in ${formatTuple(expected)}:`);
    lines.push("    raise HttpResponseError(response=_initial)");
    lines.push(
      '_polling = LROBasePolling(lro_options={"final-state-via": "azure-async-operation"}, **kwargs)',
    );
    lines.push("def _deserialize(pipeline_response):");
    if (op.lro.finalPyType === "None") {
      lines.push("    return None");
    } else {
      lines.push(
        "    payload = pipeline_response.http_response.json() if pipeline_response.http_response.content else None",
      );
      lines.push(`    return _from_dict(${op.lro.finalPyType}, payload)`);
    }
    lines.push("return LROPoller(self._client, _initial, _deserialize, _polling)");
    return lines.join("\n");
  }

  lines.push("_response = self._client.send_request(_request, **kwargs)");
  const expectedSc = op.successStatusCodes.length ? op.successStatusCodes : [200];
  lines.push(`if _response.status_code not in ${formatTuple(expectedSc)}:`);
  lines.push("    raise HttpResponseError(response=_response)");
  if (op.returnPyType === "None") {
    lines.push("return None");
  } else {
    lines.push("_payload = _response.json() if _response.content else None");
    lines.push(
      `return _from_dict(${stripOptional(op.returnPyType)}, _payload)  # type: ignore[return-value]`,
    );
  }
  return lines.join("\n");
}

/* ═══════════════════  Operation method component  ════════════════ */

function renderOperationMethod(op: SdkOperation) {
  const isLro = !!op.lro;
  const isPaged = !!op.paged;
  const methodName = isLro ? `begin_${op.pyName.replace(/^(begin_)?/, "")}` : op.pyName;
  const returnType = isLro
    ? `LROPoller[${op.lro!.finalPyType}]`
    : isPaged
      ? `ItemPaged[${op.paged!.itemPyType}]`
      : op.returnPyType;

  const params: Param[] = [];
  for (const p of op.pathParameters) params.push({ name: p.pyName, type: p.pyType });
  if (op.bodyParameter)
    params.push({ name: op.bodyParameter.pyName, type: op.bodyParameter.pyType });

  const kwOnly: Param[] = [];
  for (const p of op.queryParameters) {
    if (p.serializedName === "api-version") continue;
    kwOnly.push({ name: p.pyName, type: `Optional[${p.pyType}]`, default: null as any });
  }
  for (const p of op.headerParameters) {
    if (p.serializedName.toLowerCase() === "content-type") continue;
    kwOnly.push({ name: p.pyName, type: `Optional[${p.pyType}]`, default: null as any });
  }
  if (kwOnly.length) {
    params.push("*");
    params.push(...kwOnly);
  }

  return (
    <alloyPy.MethodDeclaration name={methodName} parameters={params} kwargs returnType={returnType}>
      {`"""${docstring(op.docstring ?? op.name)}"""\n${buildOpBody(op)}`}
    </alloyPy.MethodDeclaration>
  );
}

/* ═══════════════════════  Render tree  ═══════════════════════════ */

function renderTree(shape: SdkShape, program: EmitContext<HelloPythonEmitterOptions>["program"]) {
  const opsClass = `${shape.serviceName}Operations`;
  const hasPaged = shape.operations.some((o) => o.paged);
  const hasLro = shape.operations.some((o) => o.lro);

  /* ── import blocks (string) ────────────────────────────────── */

  const configImports = [
    "from typing import Any, TYPE_CHECKING",
    "",
    "from azure.core.pipeline import policies",
    "",
    "from ._version import VERSION",
    "",
    "if TYPE_CHECKING:",
    "    from azure.core.credentials import TokenCredential",
  ].join("\n");

  const credParam: Param | null =
    shape.auth.kind === "AAD" || shape.auth.kind === "Bearer"
      ? { name: "credential", type: '"TokenCredential"' }
      : shape.auth.kind === "ApiKey"
        ? { name: "credential", type: "str" }
        : null;

  const clientImports = [
    "from typing import Any, TYPE_CHECKING",
    "",
    "from azure.core import PipelineClient",
    "from azure.core.pipeline import policies",
    "from azure.core.rest import HttpRequest, HttpResponse",
    "",
    `from ._configuration import ${shape.clientName}Configuration`,
    `from .operations._operations import ${opsClass}`,
    "",
    "if TYPE_CHECKING:",
    "    from azure.core.credentials import TokenCredential",
  ].join("\n");

  const vendorImports = [
    "import datetime",
    "from typing import Any, Mapping, Optional, Type, TypeVar",
    "",
    "T = TypeVar('T')",
  ].join("\n");

  const opsImportLines = [
    "from typing import Any, Optional",
    "",
    "from azure.core.exceptions import HttpResponseError",
  ];
  if (hasPaged) opsImportLines.push("from azure.core.paging import ItemPaged");
  if (hasLro) {
    opsImportLines.push("from azure.core.polling import LROPoller");
    opsImportLines.push("from azure.core.polling.base_polling import LROBasePolling");
  }
  opsImportLines.push("from azure.core.rest import HttpRequest");
  opsImportLines.push("");
  opsImportLines.push("from .._vendor import _api_version_query, _from_dict, _to_dict");
  const modelNames = Array.from(new Set(shape.models.map((m) => m.pyName)));
  if (modelNames.length)
    opsImportLines.push(`from ..models._models import ${modelNames.join(", ")}`);
  const enumNames = Array.from(new Set(shape.enums.map((e) => e.pyName)));
  if (enumNames.length) opsImportLines.push(`from ..models._enums import ${enumNames.join(", ")}`);

  const modelsImportLines = [
    "from __future__ import annotations",
    "",
    "import datetime",
    "import decimal",
    "from typing import Any, ClassVar, Dict, List, Mapping, Optional",
    "",
    "from .._vendor import _from_dict, _parse_datetime, _to_dict",
  ];
  if (enumNames.length) modelsImportLines.push(`from ._enums import ${enumNames.join(", ")}`);

  /* ── __init__.py contents ─────────────────────────────────── */

  const topInit = [
    `from ._client import ${shape.clientName}`,
    "from ._version import VERSION as __version__",
    "",
    `__all__ = ["${shape.clientName}", "__version__"]`,
  ].join("\n");

  const opsInit = `from ._operations import ${opsClass}\n\n__all__ = ["${opsClass}"]`;

  const allNames = [...shape.models.map((m) => m.pyName), ...shape.enums.map((e) => e.pyName)];
  const modelsInitLines: string[] = [];
  if (shape.models.length)
    modelsInitLines.push(`from ._models import ${shape.models.map((m) => m.pyName).join(", ")}`);
  if (shape.enums.length)
    modelsInitLines.push(`from ._enums import ${shape.enums.map((e) => e.pyName).join(", ")}`);
  modelsInitLines.push("");
  modelsInitLines.push(
    allNames.length
      ? `__all__ = [${allNames.map((n) => `"${n}"`).join(", ")}]`
      : "__all__: list[str] = []",
  );

  /* ── Configuration class ──────────────────────────────────── */

  const configCtorParams: Param[] = [
    { name: "endpoint", type: "str" },
    ...(credParam ? [credParam] : []),
    "*",
    { name: "api_version", type: "str", default: shape.defaultApiVersion },
  ];

  const configInitBody: string[] = ["self.endpoint = endpoint"];
  if (shape.auth.kind !== "None") configInitBody.push("self.credential = credential");
  configInitBody.push("self.api_version = api_version");
  if (shape.auth.kind === "AAD") {
    const scopes = shape.auth.scopes.length
      ? shape.auth.scopes.map((s) => `"${s}"`).join(", ")
      : '"https://management.azure.com/.default"';
    configInitBody.push(`self.credential_scopes = kwargs.pop("credential_scopes", [${scopes}])`);
  }
  configInitBody.push(`kwargs.setdefault("sdk_moniker", f"${shape.packageName}/{VERSION}")`);
  configInitBody.push("self._configure(**kwargs)");

  const configureBody: string[] = [
    'self.user_agent_policy = kwargs.get("user_agent_policy") or policies.UserAgentPolicy(**kwargs)',
    'self.headers_policy = kwargs.get("headers_policy") or policies.HeadersPolicy(**kwargs)',
    'self.proxy_policy = kwargs.get("proxy_policy") or policies.ProxyPolicy(**kwargs)',
    'self.logging_policy = kwargs.get("logging_policy") or policies.NetworkTraceLoggingPolicy(**kwargs)',
    'self.http_logging_policy = kwargs.get("http_logging_policy") or policies.HttpLoggingPolicy(**kwargs)',
    'self.custom_hook_policy = kwargs.get("custom_hook_policy") or policies.CustomHookPolicy(**kwargs)',
    'self.redirect_policy = kwargs.get("redirect_policy") or policies.RedirectPolicy(**kwargs)',
    'self.retry_policy = kwargs.get("retry_policy") or policies.RetryPolicy(**kwargs)',
  ];
  if (shape.auth.kind === "AAD") {
    configureBody.push(
      'self.authentication_policy = kwargs.get("authentication_policy") or policies.BearerTokenCredentialPolicy(',
    );
    configureBody.push("    self.credential, *self.credential_scopes, **kwargs");
    configureBody.push(")");
  } else if (shape.auth.kind === "ApiKey") {
    configureBody.push(
      'self.authentication_policy = kwargs.get("authentication_policy") or policies.AzureKeyCredentialPolicy(',
    );
    configureBody.push(`    self.credential, "${shape.auth.name}", **kwargs`);
    configureBody.push(")");
  } else {
    configureBody.push('self.authentication_policy = kwargs.get("authentication_policy")');
  }

  /* ── Client class ─────────────────────────────────────────── */

  const clientCtorParams: Param[] = [
    { name: "endpoint", type: "str" },
    ...(credParam ? [credParam] : []),
    "*",
    { name: "api_version", type: "str", default: shape.defaultApiVersion },
  ];

  const clientInitBody: string[] = [];
  clientInitBody.push(`self._config = ${shape.clientName}Configuration(`);
  clientInitBody.push("    endpoint=endpoint,");
  if (shape.auth.kind !== "None") clientInitBody.push("    credential=credential,");
  clientInitBody.push("    api_version=api_version,");
  clientInitBody.push("    **kwargs,");
  clientInitBody.push(")");
  clientInitBody.push('_policies = kwargs.pop("policies", None)');
  clientInitBody.push("if _policies is None:");
  clientInitBody.push("    _policies = [");
  clientInitBody.push("        policies.RequestIdPolicy(**kwargs),");
  clientInitBody.push("        self._config.headers_policy,");
  clientInitBody.push("        self._config.user_agent_policy,");
  clientInitBody.push("        self._config.proxy_policy,");
  clientInitBody.push("        policies.ContentDecodePolicy(**kwargs),");
  clientInitBody.push("        self._config.redirect_policy,");
  clientInitBody.push("        self._config.retry_policy,");
  clientInitBody.push("        self._config.authentication_policy,");
  clientInitBody.push("        self._config.custom_hook_policy,");
  clientInitBody.push("        self._config.logging_policy,");
  clientInitBody.push("    ]");
  clientInitBody.push(
    "self._client: PipelineClient = PipelineClient(base_url=endpoint, policies=_policies, **kwargs)",
  );
  clientInitBody.push(`self.${snake(shape.serviceName)} = ${opsClass}(self._client, self._config)`);

  const clientDocLines = [
    `"""${docstring(shape.serviceName)}`,
    "",
    `:ivar ${snake(shape.serviceName)}: ${shape.serviceName}Operations operations`,
    `:vartype ${snake(shape.serviceName)}: ${shape.moduleName}.operations.${opsClass}`,
    ":param endpoint: Service endpoint URL.",
    ":type endpoint: str",
  ];
  if (shape.auth.kind === "AAD" || shape.auth.kind === "Bearer") {
    clientDocLines.push(":param credential: Credential needed for the client to connect to Azure.");
    clientDocLines.push(":type credential: ~azure.core.credentials.TokenCredential");
  } else if (shape.auth.kind === "ApiKey") {
    clientDocLines.push(":param credential: API key credential.");
    clientDocLines.push(":type credential: str");
  }
  clientDocLines.push(
    `:keyword api_version: The API version to use. Default value is "${shape.defaultApiVersion}".`,
  );
  clientDocLines.push(":paramtype api_version: str");
  clientDocLines.push('"""');

  /* ═══════════════════════  JSX tree  ═══════════════════════════ */

  return (
    <Output
      program={program}
      externals={[alloyPy.dataclassesModule, alloyPy.abcModule, alloyPy.enumModule]}
      printWidth={120}
      tabWidth={4}
    >
      {/* ── top-level __init__.py ───────────────────────────────── */}
      <alloyPy.SourceFile path="__init__.py" headerComment={HEADER_TEXT}>
        {topInit}
      </alloyPy.SourceFile>

      {/* ── _version.py ─────────────────────────────────────────── */}
      <alloyPy.SourceFile path="_version.py" headerComment={HEADER_TEXT}>
        {`VERSION = "${shape.version}"`}
      </alloyPy.SourceFile>

      {/* ── _configuration.py ───────────────────────────────────── */}
      <alloyPy.SourceFile path="_configuration.py" headerComment={HEADER_TEXT}>
        {configImports}
        {"\n\n"}
        <alloyPy.ClassDeclaration name={`${shape.clientName}Configuration`}>
          {`"""Configuration for ${shape.clientName}.\n\nNote that all parameters used to create this instance are saved as instance attributes.\n"""\n`}

          <alloyPy.DunderMethodDeclaration
            name="__init__"
            parameters={configCtorParams}
            kwargs
            returnType="None"
          >
            {configInitBody.join("\n")}
          </alloyPy.DunderMethodDeclaration>
          {"\n"}
          <alloyPy.MethodDeclaration name="_configure" kwargs returnType="None">
            {configureBody.join("\n")}
          </alloyPy.MethodDeclaration>
        </alloyPy.ClassDeclaration>
      </alloyPy.SourceFile>

      {/* ── _client.py ──────────────────────────────────────────── */}
      <alloyPy.SourceFile path="_client.py" headerComment={HEADER_TEXT}>
        {clientImports}
        {"\n\n"}
        <alloyPy.ClassDeclaration name={shape.clientName}>
          {clientDocLines.join("\n") + "\n"}

          <alloyPy.DunderMethodDeclaration
            name="__init__"
            parameters={clientCtorParams}
            kwargs
            returnType="None"
          >
            {clientInitBody.join("\n")}
          </alloyPy.DunderMethodDeclaration>
          {"\n"}
          <alloyPy.MethodDeclaration
            name="send_request"
            parameters={[
              { name: "request", type: "HttpRequest" },
              "*",
              { name: "stream", type: "bool", default: false as any },
            ]}
            kwargs
            returnType="HttpResponse"
          >
            {`"""Run the network request through the client's chained policies."""\nreturn self._client.send_request(request, stream=stream, **kwargs)  # type: ignore`}
          </alloyPy.MethodDeclaration>
          {"\n"}
          <alloyPy.MethodDeclaration name="close" returnType="None">
            {"self._client.close()"}
          </alloyPy.MethodDeclaration>
          {"\n"}
          <alloyPy.DunderMethodDeclaration name="__enter__" returnType={`"${shape.clientName}"`}>
            {"self._client.__enter__()\nreturn self"}
          </alloyPy.DunderMethodDeclaration>
          {"\n"}
          <alloyPy.DunderMethodDeclaration
            name="__exit__"
            parameters={[{ name: "exc_type" }, { name: "exc_val" }, { name: "exc_tb" }]}
            returnType="None"
          >
            {"self._client.__exit__(exc_type, exc_val, exc_tb)"}
          </alloyPy.DunderMethodDeclaration>
        </alloyPy.ClassDeclaration>
      </alloyPy.SourceFile>

      {/* ── _vendor.py ──────────────────────────────────────────── */}
      <alloyPy.SourceFile path="_vendor.py" headerComment={HEADER_TEXT}>
        {vendorImports}

        <alloyPy.FunctionDeclaration
          name="_api_version_query"
          parameters={[{ name: "config", type: "Any" }]}
          returnType="dict"
        >
          {`"""Build the api-version query-string dict from a client configuration."""\nreturn {"api-version": config.api_version}`}
        </alloyPy.FunctionDeclaration>

        <alloyPy.FunctionDeclaration
          name="_to_dict"
          parameters={[{ name: "value", type: "Any" }]}
          returnType="Any"
        >
          {[
            "if value is None:",
            "    return None",
            'if hasattr(value, "as_dict"):',
            "    return value.as_dict()",
            "if isinstance(value, (list, tuple)):",
            "    return [_to_dict(v) for v in value]",
            "if isinstance(value, dict):",
            "    return {k: _to_dict(v) for k, v in value.items()}",
            "if isinstance(value, datetime.datetime):",
            "    return value.isoformat()",
            "return value",
          ].join("\n")}
        </alloyPy.FunctionDeclaration>

        <alloyPy.FunctionDeclaration
          name="_from_dict"
          parameters={[
            { name: "cls", type: "Type[T]" },
            { name: "value", type: "Any" },
          ]}
          returnType="Optional[T]"
        >
          {[
            "if value is None:",
            "    return None",
            'if hasattr(cls, "from_dict"):',
            "    return cls.from_dict(value)  # type: ignore[return-value]",
            "return value  # type: ignore[return-value]",
          ].join("\n")}
        </alloyPy.FunctionDeclaration>

        <alloyPy.FunctionDeclaration
          name="_parse_datetime"
          parameters={[{ name: "value", type: "Any" }]}
          returnType="Optional[datetime.datetime]"
        >
          {[
            "if value is None:",
            "    return None",
            "if isinstance(value, datetime.datetime):",
            "    return value",
            "if isinstance(value, str):",
            '    return datetime.datetime.fromisoformat(value.replace("Z", "+00:00"))',
            "return value",
          ].join("\n")}
        </alloyPy.FunctionDeclaration>
      </alloyPy.SourceFile>

      <CoreSourceFile path="py.typed" filetype="text">
        {""}
      </CoreSourceFile>

      {/* ── operations/ ─────────────────────────────────────────── */}
      <SourceDirectory path="operations">
        <alloyPy.SourceFile path="__init__.py" headerComment={HEADER_TEXT}>
          {opsInit}
        </alloyPy.SourceFile>

        <alloyPy.SourceFile path="_operations.py" headerComment={HEADER_TEXT}>
          {opsImportLines.join("\n")}
          {"\n\n"}
          <alloyPy.ClassDeclaration name={opsClass}>
            {`"""${docstring(`${shape.serviceName} operations`)}"""\n`}

            <alloyPy.DunderMethodDeclaration
              name="__init__"
              parameters={[{ name: "client" }, { name: "config" }]}
              returnType="None"
            >
              {"self._client = client\nself._config = config"}
            </alloyPy.DunderMethodDeclaration>

            {shape.operations.map((op) => ["\n", renderOperationMethod(op)])}
          </alloyPy.ClassDeclaration>
        </alloyPy.SourceFile>
      </SourceDirectory>

      {/* ── models/ ─────────────────────────────────────────────── */}
      <SourceDirectory path="models">
        <alloyPy.SourceFile path="__init__.py" headerComment={HEADER_TEXT}>
          {modelsInitLines.join("\n")}
        </alloyPy.SourceFile>

        <alloyPy.SourceFile path="_models.py" headerComment={HEADER_TEXT}>
          {modelsImportLines.join("\n")}
          {"\n\n"}
          {shape.models.length
            ? shape.models.map((m, i) => [i > 0 && "\n\n", renderModelClass(m)])
            : "# (no user-defined models found)"}
        </alloyPy.SourceFile>

        <alloyPy.SourceFile path="_enums.py" headerComment={HEADER_TEXT}>
          {"from enum import Enum"}
          {"\n\n"}
          {shape.enums.length
            ? shape.enums.map((e, i) => [i > 0 && "\n\n", renderEnumClass(e)])
            : "# (no enums found)"}
        </alloyPy.SourceFile>

        <CoreSourceFile path="_patch.py" filetype="text">
          {buildPatch()}
        </CoreSourceFile>
      </SourceDirectory>
    </Output>
  );
}

export const alloyRenderer: Renderer = {
  id: RID,
  description:
    "@alloy-js/python ClassDeclaration, MethodDeclaration, and FunctionDeclaration components for all Python constructs; method bodies as string children.",
  async emit(context: EmitContext<HelloPythonEmitterOptions>, shape, outputDir) {
    const tree = renderTree(shape, context.program);
    await writeOutput(context.program, tree, outputDir);
  },
};
