import { SourceDirectory, SourceFile as CoreSourceFile } from "@alloy-js/core";
import * as alloyPy from "@alloy-js/python";
import type { EmitContext } from "@typespec/compiler";
import { Output, writeOutput } from "@typespec/emitter-framework";
import type { HelloPythonEmitterOptions } from "../lib.js";
import type { SdkShape } from "../sdk-ir.js";
import * as py from "./python-builders.js";
import type { Renderer } from "./types.js";

/* ──────────────────────────────────────────────────────────────────
 * Alloy renderer — composes Python files via `@alloy-js/python`
 * SourceFile components. Header comments, the file scope, and
 * `__init__.py` placement come from Alloy; the per-construct Python
 * bodies still come from the shared `python-builders` so all four
 * renderers produce comparable output.
 *
 * Tradeoff: Alloy ships rich per-construct components (ClassDeclaration,
 * MethodDeclaration, DataclassDeclaration, …) that we could substitute
 * for the string snippets. We don't here because LRO/paged operation
 * bodies (closures with cross-references to `_polling`, `_extract`,
 * etc.) are easier to express as one string than as a JSX tree. The
 * `<py.SourceFile>` wrapper still demonstrates Alloy's filesystem
 * scoping and header handling.
 * ────────────────────────────────────────────────────────────── */

const RID = "alloy";
const HEADER_TEXT = `Generated by @typespec/hello-python-emitter [${RID} renderer]. Do not edit by hand.`;

/**
 * Strip the `# Generated by …\n\n` line that `python-builders` prepends —
 * `<py.SourceFile headerComment>` emits its own version.
 */
function stripHeader(content: string): string {
  return content.replace(/^# Generated by [^\n]*\n\n?/, "");
}

function renderTree(shape: SdkShape, program: EmitContext<HelloPythonEmitterOptions>["program"]) {
  const opsClass = `${shape.serviceName}Operations`;
  return (
    <Output
      program={program}
      namePolicy={alloyPy.createPythonNamePolicy()}
      externals={[
        alloyPy.dataclassesModule,
        alloyPy.abcModule,
        alloyPy.enumModule,
      ]}
      printWidth={120}
      tabWidth={4}
    >
      <alloyPy.SourceFile path="__init__.py" headerComment={HEADER_TEXT}>
        {stripHeader(py.buildTopInit(RID, shape))}
      </alloyPy.SourceFile>
      <alloyPy.SourceFile path="_version.py" headerComment={HEADER_TEXT}>
        {stripHeader(py.buildVersion(RID, shape))}
      </alloyPy.SourceFile>
      <alloyPy.SourceFile path="_configuration.py" headerComment={HEADER_TEXT}>
        {stripHeader(py.buildConfiguration(RID, shape))}
      </alloyPy.SourceFile>
      <alloyPy.SourceFile path="_client.py" headerComment={HEADER_TEXT}>
        {stripHeader(py.buildClient(RID, shape, opsClass))}
      </alloyPy.SourceFile>
      <alloyPy.SourceFile path="_vendor.py" headerComment={HEADER_TEXT}>
        {stripHeader(py.buildVendor(RID))}
      </alloyPy.SourceFile>
      <CoreSourceFile path="py.typed" filetype="text">
        {""}
      </CoreSourceFile>

      <SourceDirectory path="operations">
        <alloyPy.SourceFile path="__init__.py" headerComment={HEADER_TEXT}>
          {stripHeader(py.buildOperationsInit(RID, opsClass))}
        </alloyPy.SourceFile>
        <alloyPy.SourceFile path="_operations.py" headerComment={HEADER_TEXT}>
          {stripHeader(py.buildOperations(RID, shape, opsClass))}
        </alloyPy.SourceFile>
      </SourceDirectory>

      <SourceDirectory path="models">
        <alloyPy.SourceFile path="__init__.py" headerComment={HEADER_TEXT}>
          {stripHeader(py.buildModelsInit(RID, shape))}
        </alloyPy.SourceFile>
        <alloyPy.SourceFile path="_models.py" headerComment={HEADER_TEXT}>
          {stripHeader(py.buildModels(RID, shape))}
        </alloyPy.SourceFile>
        <alloyPy.SourceFile path="_enums.py" headerComment={HEADER_TEXT}>
          {stripHeader(py.buildEnums(RID, shape))}
        </alloyPy.SourceFile>
        <CoreSourceFile path="_patch.py" filetype="text">
          {py.buildPatch()}
        </CoreSourceFile>
      </SourceDirectory>
    </Output>
  );
}

export const alloyRenderer: Renderer = {
  id: RID,
  description: "@alloy-js/python SourceFile components scaffold each Python file; bodies come from shared snippets.",
  async emit(context: EmitContext<HelloPythonEmitterOptions>, shape, outputDir) {
    const tree = renderTree(shape, context.program);
    await writeOutput(context.program, tree, outputDir);
  },
};
