import { SourceDirectory, SourceFile as CoreSourceFile } from "@alloy-js/core";
import * as alloyPy from "@alloy-js/python";
import type { EmitContext } from "@typespec/compiler";
import { Output, writeOutput } from "@typespec/emitter-framework";
import {
  ClassDeclaration as EfClassDeclaration,
  EnumDeclaration as EfEnumDeclaration,
  datetimeModule,
  typingModule,
} from "@typespec/emitter-framework/python";
import type { HelloPythonEmitterOptions } from "../lib.js";
import type { SdkShape } from "../sdk-ir.js";
import * as py from "./python-builders.js";
import type { Renderer } from "./types.js";

/* ──────────────────────────────────────────────────────────────────
 * EF-mix renderer — mixes `@typespec/emitter-framework/python`
 * declarative components with Alloy file scaffolding and shared
 * python-builders snippets.
 *
 *   • `<py.SourceFile>` (Alloy) — provides the file scope, header
 *      comment, and auto-managed imports.
 *   • `<ef.ClassDeclaration>` / `<ef.EnumDeclaration>` — when the
 *      target TypeSpec construct fits EF's defaults (Models become
 *      `@dataclass(kw_only=True)`, Enums become `ClassEnumDeclaration`).
 *   • `python-builders` snippets — fallback for procedural code
 *      (operations, client, configuration, vendor) and for
 *      "extensible-union" enums that EF can't render directly
 *      (it calls `$.union.isValidEnum`, which rejects unions with
 *      an open `string` variant such as Azure.Core's `OperationState`).
 *
 * To keep the file imports tractable, we pick **per-file** between
 * "all EF children" and "all python-builders snippet" rather than
 * mixing inside one SourceFile (EF auto-imports only what its
 * children declare; raw string children don't participate).
 * ────────────────────────────────────────────────────────────── */

const RID = "ef-mix";
const HEADER_TEXT = `Generated by @typespec/hello-python-emitter [${RID} renderer]. Do not edit by hand.`;

function stripHeader(content: string): string {
  return content.replace(/^# Generated by [^\n]*\n\n?/, "");
}

function modelReferencesUnionEnum(
  m: { properties: { pyType: string }[] },
  unionEnumNames: Set<string>,
): boolean {
  if (unionEnumNames.size === 0) return false;
  for (const p of m.properties) {
    for (const name of unionEnumNames) {
      const t = p.pyType;
      if (
        t === name ||
        t.includes(`[${name}]`) ||
        t.includes(`${name},`) ||
        t.includes(` ${name}`)
      ) {
        return true;
      }
    }
  }
  return false;
}

function renderTree(shape: SdkShape, program: EmitContext<HelloPythonEmitterOptions>["program"]) {
  const opsClass = `${shape.serviceName}Operations`;

  const unionEnumNames = new Set(
    shape.enums.filter((e) => e.tspEnum.kind !== "Enum").map((e) => e.pyName),
  );
  // EF can render a model only when none of its properties reference an
  // extensible-union enum that EF refuses to bind. If any model needs the
  // python-builders fallback, render the whole file via python-builders so
  // imports stay consistent.
  const canUseEfForModels =
    shape.models.length > 0 &&
    shape.models.every((m) => !modelReferencesUnionEnum(m, unionEnumNames));
  const canUseEfForEnums =
    shape.enums.length > 0 &&
    shape.enums.every((e) => e.tspEnum.kind === "Enum");

  return (
    <Output
      program={program}
      namePolicy={alloyPy.createPythonNamePolicy()}
      externals={[
        alloyPy.dataclassesModule,
        alloyPy.abcModule,
        alloyPy.enumModule,
        typingModule,
        datetimeModule,
      ]}
      printWidth={120}
      tabWidth={4}
    >
      <alloyPy.SourceFile path="__init__.py" headerComment={HEADER_TEXT}>
        {stripHeader(py.buildTopInit(RID, shape))}
      </alloyPy.SourceFile>
      <alloyPy.SourceFile path="_version.py" headerComment={HEADER_TEXT}>
        {stripHeader(py.buildVersion(RID, shape))}
      </alloyPy.SourceFile>
      <alloyPy.SourceFile path="_configuration.py" headerComment={HEADER_TEXT}>
        {stripHeader(py.buildConfiguration(RID, shape))}
      </alloyPy.SourceFile>
      <alloyPy.SourceFile path="_client.py" headerComment={HEADER_TEXT}>
        {stripHeader(py.buildClient(RID, shape, opsClass))}
      </alloyPy.SourceFile>
      <alloyPy.SourceFile path="_vendor.py" headerComment={HEADER_TEXT}>
        {stripHeader(py.buildVendor(RID))}
      </alloyPy.SourceFile>
      <CoreSourceFile path="py.typed" filetype="text">
        {""}
      </CoreSourceFile>

      <SourceDirectory path="operations">
        <alloyPy.SourceFile path="__init__.py" headerComment={HEADER_TEXT}>
          {stripHeader(py.buildOperationsInit(RID, opsClass))}
        </alloyPy.SourceFile>
        <alloyPy.SourceFile path="_operations.py" headerComment={HEADER_TEXT}>
          {stripHeader(py.buildOperations(RID, shape, opsClass))}
        </alloyPy.SourceFile>
      </SourceDirectory>

      <SourceDirectory path="models">
        <alloyPy.SourceFile path="__init__.py" headerComment={HEADER_TEXT}>
          {stripHeader(py.buildModelsInit(RID, shape))}
        </alloyPy.SourceFile>
        {canUseEfForModels ? (
          <alloyPy.SourceFile path="_models.py" headerComment={HEADER_TEXT}>
            {shape.models.map((m) => (
              <EfClassDeclaration type={m.tspModel} />
            ))}
          </alloyPy.SourceFile>
        ) : (
          <CoreSourceFile path="_models.py" filetype="text">
            {py.buildModels(RID, shape).replace(/string renderer|alloy renderer|template renderer/g, `${RID} renderer`)}
          </CoreSourceFile>
        )}
        {canUseEfForEnums ? (
          <alloyPy.SourceFile path="_enums.py" headerComment={HEADER_TEXT}>
            {shape.enums.map((e) => (
              <EfEnumDeclaration type={e.tspEnum as never} />
            ))}
          </alloyPy.SourceFile>
        ) : (
          <CoreSourceFile path="_enums.py" filetype="text">
            {py.buildEnums(RID, shape).replace(/string renderer|alloy renderer|template renderer/g, `${RID} renderer`)}
          </CoreSourceFile>
        )}
        <CoreSourceFile path="_patch.py" filetype="text">
          {py.buildPatch()}
        </CoreSourceFile>
      </SourceDirectory>
    </Output>
  );
}

export const efMixRenderer: Renderer = {
  id: "ef-mix",
  description:
    "Alloy file scaffolding + @typespec/emitter-framework/python declarative components (ClassDeclaration / EnumDeclaration) where applicable, python-builders fallback otherwise.",
  async emit(context: EmitContext<HelloPythonEmitterOptions>, shape, outputDir) {
    const tree = renderTree(shape, context.program);
    await writeOutput(context.program, tree, outputDir);
  },
};
