/**
 * Shared Python snippet builders consumed by all four renderers.
 *
 * Each function returns a multi-line string (`buildXxx`) or an array of lines
 * (`renderXxx`) representing one Python construct — a class body, an
 * operation method, an enum, a vendor helper file, etc. The renderers above
 * differ in *how* they stitch the snippets into files (template literals,
 * mustache-lite engine, Alloy components, EF components), not in the
 * substance of the Python they emit. That keeps the renderer comparison
 * apples-to-apples and the byte-diff narrow.
 */

import type {
  SdkEnum,
  SdkModel,
  SdkOperation,
  SdkProperty,
  SdkShape,
} from "../sdk-ir.js";

/* ────────────────────────────  Constants  ─────────────────────────── */

export function header(rendererId: string): string {
  return `# Generated by @typespec/hello-python-emitter [${rendererId} renderer]. Do not edit by hand.\n`;
}

/* ────────────────────────  String formatting  ─────────────────────── */

export function docstring(s: string): string {
  // TypeSpec @doc strings often already end in a period; we don't want
  // `"""docs.."""`. Strip trailing periods, then append exactly one.
  const trimmed = s.trim().replace(/\.+$/, "");
  return `${trimmed}.`;
}

export function formatTuple(values: number[]): string {
  return values.length === 1 ? `(${values[0]},)` : `(${values.join(", ")})`;
}

export function stripOptional(t: string): string {
  return t.replace(/Optional\[(.*)\]/, "$1").replace(/ \| None$/, "");
}

export function snake(s: string): string {
  return s
    .replace(/([a-z0-9])([A-Z])/g, "$1_$2")
    .replace(/([A-Z]+)([A-Z][a-z])/g, "$1_$2")
    .replace(/[-\s]+/g, "_")
    .toLowerCase();
}

/* ────────────────────────────  Vendor file  ───────────────────────── */

export function buildVendor(rendererId: string): string {
  return [
    header(rendererId),
    "import datetime",
    "from typing import Any, Mapping, Optional, Type, TypeVar",
    "",
    "T = TypeVar('T')",
    "",
    "",
    "def _api_version_query(config: Any) -> dict:",
    `    """Build the api-version query-string dict from a client configuration."""`,
    `    return {"api-version": config.api_version}`,
    "",
    "",
    "def _to_dict(value: Any) -> Any:",
    "    if value is None:",
    "        return None",
    '    if hasattr(value, "as_dict"):',
    "        return value.as_dict()",
    "    if isinstance(value, (list, tuple)):",
    "        return [_to_dict(v) for v in value]",
    "    if isinstance(value, dict):",
    "        return {k: _to_dict(v) for k, v in value.items()}",
    "    if isinstance(value, datetime.datetime):",
    "        return value.isoformat()",
    "    return value",
    "",
    "",
    "def _from_dict(cls: Type[T], value: Any) -> Optional[T]:",
    "    if value is None:",
    "        return None",
    '    if hasattr(cls, "from_dict"):',
    "        return cls.from_dict(value)  # type: ignore[return-value]",
    "    return value  # type: ignore[return-value]",
    "",
    "",
    "def _parse_datetime(value: Any) -> Optional[datetime.datetime]:",
    "    if value is None:",
    "        return None",
    "    if isinstance(value, datetime.datetime):",
    "        return value",
    "    if isinstance(value, str):",
    '        return datetime.datetime.fromisoformat(value.replace("Z", "+00:00"))',
    "    return value",
    "",
  ].join("\n");
}

/* ─────────────────────────  Configuration class  ──────────────────── */

export function buildConfiguration(rendererId: string, shape: SdkShape): string {
  const lines: string[] = [
    header(rendererId),
    "from typing import Any, TYPE_CHECKING",
    "",
    "from azure.core.pipeline import policies",
    "",
    "from ._version import VERSION",
    "",
    "if TYPE_CHECKING:",
    "    from azure.core.credentials import TokenCredential",
    "",
    "",
    `class ${shape.clientName}Configuration:`,
    `    """Configuration for ${shape.clientName}.`,
    "",
    "    Note that all parameters used to create this instance are saved as instance attributes.",
    "    \"\"\"",
    "",
  ];

  const ctorArgs = ["self", "endpoint: str"];
  if (shape.auth.kind === "AAD" || shape.auth.kind === "Bearer") {
    ctorArgs.push('credential: "TokenCredential"');
  } else if (shape.auth.kind === "ApiKey") {
    ctorArgs.push("credential: str");
  }
  ctorArgs.push("*");
  ctorArgs.push(`api_version: str = "${shape.defaultApiVersion}"`);
  ctorArgs.push("**kwargs: Any");

  lines.push("    def __init__(");
  for (const arg of ctorArgs) lines.push(`        ${arg},`);
  lines.push("    ) -> None:");
  lines.push("        self.endpoint = endpoint");
  if (shape.auth.kind !== "None") {
    lines.push("        self.credential = credential");
  }
  lines.push("        self.api_version = api_version");

  if (shape.auth.kind === "AAD") {
    const scopes = shape.auth.scopes.length
      ? shape.auth.scopes.map((s) => `"${s}"`).join(", ")
      : `"https://management.azure.com/.default"`;
    lines.push(`        self.credential_scopes = kwargs.pop("credential_scopes", [${scopes}])`);
  }

  lines.push(`        kwargs.setdefault("sdk_moniker", f"${shape.packageName}/{VERSION}")`);
  lines.push("        self._configure(**kwargs)");
  lines.push("");
  lines.push("    def _configure(self, **kwargs: Any) -> None:");
  lines.push('        self.user_agent_policy = kwargs.get("user_agent_policy") or policies.UserAgentPolicy(**kwargs)');
  lines.push('        self.headers_policy = kwargs.get("headers_policy") or policies.HeadersPolicy(**kwargs)');
  lines.push('        self.proxy_policy = kwargs.get("proxy_policy") or policies.ProxyPolicy(**kwargs)');
  lines.push('        self.logging_policy = kwargs.get("logging_policy") or policies.NetworkTraceLoggingPolicy(**kwargs)');
  lines.push('        self.http_logging_policy = kwargs.get("http_logging_policy") or policies.HttpLoggingPolicy(**kwargs)');
  lines.push('        self.custom_hook_policy = kwargs.get("custom_hook_policy") or policies.CustomHookPolicy(**kwargs)');
  lines.push('        self.redirect_policy = kwargs.get("redirect_policy") or policies.RedirectPolicy(**kwargs)');
  lines.push('        self.retry_policy = kwargs.get("retry_policy") or policies.RetryPolicy(**kwargs)');
  if (shape.auth.kind === "AAD") {
    lines.push('        self.authentication_policy = kwargs.get("authentication_policy") or policies.BearerTokenCredentialPolicy(');
    lines.push("            self.credential, *self.credential_scopes, **kwargs");
    lines.push("        )");
  } else if (shape.auth.kind === "ApiKey") {
    lines.push('        self.authentication_policy = kwargs.get("authentication_policy") or policies.AzureKeyCredentialPolicy(');
    lines.push(`            self.credential, "${shape.auth.name}", **kwargs`);
    lines.push("        )");
  } else {
    lines.push('        self.authentication_policy = kwargs.get("authentication_policy")');
  }
  lines.push("");
  return lines.join("\n");
}

/* ─────────────────────────────  Client class  ─────────────────────── */

export function buildClient(rendererId: string, shape: SdkShape, opsClass: string): string {
  const credArg =
    shape.auth.kind === "AAD" || shape.auth.kind === "Bearer"
      ? 'credential: "TokenCredential"'
      : shape.auth.kind === "ApiKey"
        ? "credential: str"
        : null;
  const ctorParams = [
    "self",
    "endpoint: str",
    credArg,
    "*",
    `api_version: str = "${shape.defaultApiVersion}"`,
    "**kwargs: Any",
  ].filter((p): p is string => p !== null);

  const credDocLines: string | null =
    shape.auth.kind === "AAD" || shape.auth.kind === "Bearer"
      ? "    :param credential: Credential needed for the client to connect to Azure.\n    :type credential: ~azure.core.credentials.TokenCredential"
      : shape.auth.kind === "ApiKey"
        ? "    :param credential: API key credential.\n    :type credential: str"
        : null;
  const credPassLine: string | null =
    shape.auth.kind !== "None" ? "            credential=credential," : null;

  return [
    header(rendererId),
    "from typing import Any, TYPE_CHECKING",
    "",
    "from azure.core import PipelineClient",
    "from azure.core.pipeline import policies",
    "from azure.core.rest import HttpRequest, HttpResponse",
    "",
    `from ._configuration import ${shape.clientName}Configuration`,
    `from .operations._operations import ${opsClass}`,
    "",
    "if TYPE_CHECKING:",
    "    from azure.core.credentials import TokenCredential",
    "",
    "",
    `class ${shape.clientName}:`,
    `    """${docstring(shape.serviceName)}`,
    "",
    `    :ivar ${snake(shape.serviceName)}: ${shape.serviceName}Operations operations`,
    `    :vartype ${snake(shape.serviceName)}: ${shape.moduleName}.operations.${opsClass}`,
    "    :param endpoint: Service endpoint URL.",
    "    :type endpoint: str",
    credDocLines,
    `    :keyword api_version: The API version to use. Default value is "${shape.defaultApiVersion}".`,
    "    :paramtype api_version: str",
    '    """',
    "",
    "    def __init__(",
    ...ctorParams.map((p) => `        ${p},`),
    "    ) -> None:",
    `        self._config = ${shape.clientName}Configuration(`,
    "            endpoint=endpoint,",
    credPassLine,
    "            api_version=api_version,",
    "            **kwargs,",
    "        )",
    '        _policies = kwargs.pop("policies", None)',
    "        if _policies is None:",
    "            _policies = [",
    "                policies.RequestIdPolicy(**kwargs),",
    "                self._config.headers_policy,",
    "                self._config.user_agent_policy,",
    "                self._config.proxy_policy,",
    "                policies.ContentDecodePolicy(**kwargs),",
    "                self._config.redirect_policy,",
    "                self._config.retry_policy,",
    "                self._config.authentication_policy,",
    "                self._config.custom_hook_policy,",
    "                self._config.logging_policy,",
    "            ]",
    "        self._client: PipelineClient = PipelineClient(base_url=endpoint, policies=_policies, **kwargs)",
    `        self.${snake(shape.serviceName)} = ${opsClass}(self._client, self._config)`,
    "",
    "    def send_request(",
    "        self,",
    "        request: HttpRequest,",
    "        *,",
    "        stream: bool = False,",
    "        **kwargs: Any,",
    "    ) -> HttpResponse:",
    '        """Run the network request through the client\'s chained policies."""',
    "        return self._client.send_request(request, stream=stream, **kwargs)  # type: ignore",
    "",
    "    def close(self) -> None:",
    "        self._client.close()",
    "",
    `    def __enter__(self) -> "${shape.clientName}":`,
    "        self._client.__enter__()",
    "        return self",
    "",
    "    def __exit__(self, *exc_details: Any) -> None:",
    "        self._client.__exit__(*exc_details)",
    "",
  ]
    .filter((l): l is string => l !== null)
    .join("\n");
}

/* ─────────────────────  operations/_operations.py  ────────────────── */

export function buildOperations(rendererId: string, shape: SdkShape, opsClass: string): string {
  const hasPaged = shape.operations.some((o) => o.paged);
  const hasLro = shape.operations.some((o) => o.lro);
  const lines: string[] = [
    header(rendererId),
    "from typing import Any, Optional",
    "",
    "from azure.core.exceptions import HttpResponseError",
  ];
  if (hasPaged) lines.push("from azure.core.paging import ItemPaged");
  if (hasLro) {
    lines.push("from azure.core.polling import LROPoller");
    lines.push("from azure.core.polling.base_polling import LROBasePolling");
  }
  lines.push("from azure.core.rest import HttpRequest");
  lines.push("");
  lines.push("from .._vendor import _api_version_query, _from_dict, _to_dict");

  const modelNames = Array.from(new Set(shape.models.map((m) => m.pyName)));
  if (modelNames.length) {
    lines.push(`from ..models._models import ${modelNames.join(", ")}`);
  }
  const enumNames = Array.from(new Set(shape.enums.map((e) => e.pyName)));
  if (enumNames.length) {
    lines.push(`from ..models._enums import ${enumNames.join(", ")}`);
  }
  lines.push("");
  lines.push("");
  lines.push(`class ${opsClass}:`);
  lines.push(`    """${docstring(`${shape.serviceName} operations`)}"""`);
  lines.push("");
  lines.push("    def __init__(self, client, config) -> None:");
  lines.push("        self._client = client");
  lines.push("        self._config = config");
  lines.push("");

  for (const op of shape.operations) {
    lines.push(...renderOperation(op, "    "));
    lines.push("");
  }
  return lines.join("\n");
}

export function renderOperation(op: SdkOperation, indent: string): string[] {
  const i = indent;
  const i2 = indent + "    ";
  const lines: string[] = [];

  const isLro = !!op.lro;
  const isPaged = !!op.paged;
  const methodName = isLro ? `begin_${op.pyName.replace(/^(begin_)?/, "")}` : op.pyName;
  const returnType = isLro
    ? `LROPoller[${op.lro!.finalPyType}]`
    : isPaged
      ? `ItemPaged[${op.paged!.itemPyType}]`
      : op.returnPyType;

  const positional: string[] = ["self"];
  const keyword: string[] = [];
  for (const p of op.pathParameters) positional.push(`${p.pyName}: ${p.pyType}`);
  if (op.bodyParameter) positional.push(`${op.bodyParameter.pyName}: ${op.bodyParameter.pyType}`);
  for (const p of op.queryParameters) {
    if (p.serializedName === "api-version") continue;
    keyword.push(`${p.pyName}: Optional[${p.pyType}] = None`);
  }
  for (const p of op.headerParameters) {
    if (p.serializedName.toLowerCase() === "content-type") continue;
    keyword.push(`${p.pyName}: Optional[${p.pyType}] = None`);
  }
  const allArgs = keyword.length
    ? [...positional, "*", ...keyword, "**kwargs: Any"]
    : [...positional, "**kwargs: Any"];

  lines.push(`${i}def ${methodName}(`);
  for (const a of allArgs) lines.push(`${i2}${a},`);
  lines.push(`${i}) -> ${returnType}:`);
  lines.push(`${i2}"""${docstring(op.docstring ?? op.name)}"""`);

  const pathExpr = formatPath(op);
  const queryParts: string[] = ["**_api_version_query(self._config)"];
  for (const p of op.queryParameters) {
    if (p.serializedName === "api-version") continue;
    queryParts.push(`"${p.serializedName}": ${p.pyName}`);
  }

  const headerLines: string[] = [];
  const hasUserContentType = op.headerParameters.some(
    (p) => p.serializedName.toLowerCase() === "content-type",
  );
  if (op.bodyParameter) {
    const ct = hasUserContentType && op.verb === "patch"
      ? "application/merge-patch+json"
      : "application/json";
    headerLines.push(`"Content-Type": "${ct}"`);
  }
  for (const p of op.headerParameters) {
    if (p.serializedName.toLowerCase() === "content-type") continue;
    headerLines.push(`"${p.serializedName}": ${p.pyName}`);
  }

  lines.push(`${i2}_params: dict = {${queryParts.join(", ")}}`);
  if (op.queryParameters.some((p) => p.serializedName !== "api-version")) {
    lines.push(`${i2}_params = {k: v for k, v in _params.items() if v is not None}`);
  }
  if (headerLines.length) {
    lines.push(`${i2}_headers: dict = {${headerLines.join(", ")}}`);
    lines.push(`${i2}_headers = {k: v for k, v in _headers.items() if v is not None}`);
  }
  if (op.bodyParameter) {
    lines.push(`${i2}_body = _to_dict(${op.bodyParameter.pyName})`);
  }

  if (isPaged) {
    lines.push(`${i2}def _prepare(next_link: Optional[str] = None) -> HttpRequest:`);
    lines.push(`${i2}    if next_link is None:`);
    lines.push(`${i2}        return HttpRequest("${op.verb.toUpperCase()}", ${pathExpr}, params=_params${headerLines.length ? ", headers=_headers" : ""})`);
    lines.push(`${i2}    return HttpRequest("GET", next_link)`);
    lines.push("");
    lines.push(`${i2}def _extract(pipeline_response):`);
    lines.push(`${i2}    payload = pipeline_response.http_response.json()`);
    lines.push(`${i2}    items = [_from_dict(${op.paged!.itemPyType}, v) for v in payload.get("${op.paged!.itemsPath}", [])]`);
    const nextKey = op.paged!.nextLinkPath ?? "nextLink";
    lines.push(`${i2}    return payload.get("${nextKey}"), iter(items)`);
    lines.push("");
    lines.push(`${i2}def _get_next(next_link: Optional[str] = None):`);
    lines.push(`${i2}    request = _prepare(next_link)`);
    lines.push(`${i2}    return self._client._pipeline.run(request, stream=False, **kwargs)`);
    lines.push("");
    lines.push(`${i2}return ItemPaged(_get_next, _extract)`);
    return lines;
  }

  const reqExtras: string[] = ["params=_params"];
  if (headerLines.length) reqExtras.push("headers=_headers");
  if (op.bodyParameter) reqExtras.push("json=_body");
  lines.push(`${i2}_request = HttpRequest("${op.verb.toUpperCase()}", ${pathExpr}, ${reqExtras.join(", ")})`);

  if (isLro) {
    const lroExpected = op.successStatusCodes.length ? op.successStatusCodes : [200, 201, 202, 204];
    lines.push(`${i2}_initial = self._client.send_request(_request, **kwargs)`);
    lines.push(`${i2}if _initial.status_code not in ${formatTuple(lroExpected)}:`);
    lines.push(`${i2}    raise HttpResponseError(response=_initial)`);
    lines.push(`${i2}_polling = LROBasePolling(lro_options={"final-state-via": "azure-async-operation"}, **kwargs)`);
    lines.push(`${i2}def _deserialize(pipeline_response):`);
    if (op.lro!.finalPyType === "None") {
      lines.push(`${i2}    return None`);
    } else {
      lines.push(`${i2}    payload = pipeline_response.http_response.json() if pipeline_response.http_response.content else None`);
      lines.push(`${i2}    return _from_dict(${op.lro!.finalPyType}, payload)`);
    }
    lines.push(`${i2}return LROPoller(self._client, _initial, _deserialize, _polling)`);
    return lines;
  }

  lines.push(`${i2}_response = self._client.send_request(_request, **kwargs)`);
  const expectedSc = op.successStatusCodes.length ? op.successStatusCodes : [200];
  lines.push(`${i2}if _response.status_code not in ${formatTuple(expectedSc)}:`);
  lines.push(`${i2}    raise HttpResponseError(response=_response)`);
  if (op.returnPyType === "None") {
    lines.push(`${i2}return None`);
  } else {
    lines.push(`${i2}_payload = _response.json() if _response.content else None`);
    lines.push(`${i2}return _from_dict(${stripOptional(op.returnPyType)}, _payload)  # type: ignore[return-value]`);
  }
  return lines;
}

function formatPath(op: SdkOperation): string {
  if (op.pathParameters.length === 0) return `"${op.path}"`;
  let s = op.path;
  for (const p of op.pathParameters) {
    s = s.replace(`{${p.serializedName}}`, `{${p.pyName}}`);
  }
  return `f"${s}"`;
}

/* ──────────────────────────────  Models  ──────────────────────────── */

export function buildModels(rendererId: string, shape: SdkShape): string {
  const lines: string[] = [
    header(rendererId),
    "from __future__ import annotations",
    "",
    "import datetime",
    "import decimal",
    "from typing import Any, ClassVar, Dict, List, Mapping, Optional",
    "",
    "from .._vendor import _from_dict, _parse_datetime, _to_dict",
  ];
  const enumNames = shape.enums.map((e) => e.pyName);
  if (enumNames.length) {
    lines.push(`from ._enums import ${enumNames.join(", ")}`);
  }
  lines.push("");
  lines.push("");
  if (!shape.models.length) {
    lines.push("# (no user-defined models found)");
    lines.push("");
    return lines.join("\n");
  }
  for (const m of shape.models) {
    lines.push(...renderModel(m));
    lines.push("");
  }
  return lines.join("\n");
}

export function renderModel(m: SdkModel): string[] {
  const i = "    ";
  const lines: string[] = [];
  lines.push(`class ${m.pyName}:`);
  lines.push(`${i}"""${docstring(m.docstring ?? m.name)}"""`);
  if (m.properties.length === 0) {
    lines.push(`${i}pass`);
    return lines;
  }

  const required = m.properties.filter((p) => !p.optional);
  const optional = m.properties.filter((p) => p.optional);

  lines.push("");
  for (const p of required) lines.push(`${i}${p.pyName}: ${p.pyType}`);
  for (const p of optional) lines.push(`${i}${p.pyName}: Optional[${p.pyType}] = None`);
  lines.push("");

  lines.push(`${i}_SERIALIZED_NAMES: ClassVar[Dict[str, str]] = {`);
  for (const p of m.properties) {
    lines.push(`${i}    "${p.pyName}": "${p.serializedName}",`);
  }
  lines.push(`${i}}`);
  lines.push("");

  lines.push(`${i}def __init__(`);
  lines.push(`${i}    self,`);
  lines.push(`${i}    *,`);
  for (const p of required) lines.push(`${i}    ${p.pyName}: ${p.pyType},`);
  for (const p of optional) lines.push(`${i}    ${p.pyName}: Optional[${p.pyType}] = None,`);
  lines.push(`${i}) -> None:`);
  for (const p of m.properties) lines.push(`${i}    self.${p.pyName} = ${p.pyName}`);
  lines.push("");

  lines.push(`${i}def as_dict(self) -> Dict[str, Any]:`);
  lines.push(`${i}    d: Dict[str, Any] = {}`);
  for (const p of m.properties) {
    lines.push(`${i}    if self.${p.pyName} is not None:`);
    lines.push(`${i}        d["${p.serializedName}"] = _to_dict(self.${p.pyName})`);
  }
  lines.push(`${i}    return d`);
  lines.push("");
  lines.push(`${i}@classmethod`);
  lines.push(`${i}def from_dict(cls, data: Mapping[str, Any]) -> "${m.pyName}":`);
  lines.push(`${i}    return cls(`);
  for (const p of m.properties) {
    lines.push(`${i}        ${p.pyName}=${decodeExpr(p)},`);
  }
  lines.push(`${i}    )`);
  return lines;
}

function decodeExpr(p: SdkProperty): string {
  const key = `data.get("${p.serializedName}")`;
  const t = p.pyType;
  if (t.startsWith("list[")) {
    const inner = t.slice(5, -1);
    return `[${decodeScalar(inner, "v")} for v in (${key} or [])]`;
  }
  if (t.startsWith("dict[")) {
    return key;
  }
  return decodeScalar(t, key);
}

function decodeScalar(t: string, src: string): string {
  if (t === "str" || t === "bool" || t === "int" || t === "float" || t === "Any" || t === "bytes") {
    return src;
  }
  if (t === "datetime.datetime") return `_parse_datetime(${src})`;
  if (t === "datetime.date" || t === "datetime.time" || t === "datetime.timedelta") return src;
  if (t === "decimal.Decimal") return `decimal.Decimal(${src}) if ${src} is not None else None`;
  return `_from_dict(${t}, ${src})`;
}

/* ───────────────────────────────  Enums  ──────────────────────────── */

export function buildEnums(rendererId: string, shape: SdkShape): string {
  const lines: string[] = [header(rendererId), "from enum import Enum", "", ""];
  if (!shape.enums.length) {
    lines.push("# (no enums found)");
    lines.push("");
    return lines.join("\n");
  }
  for (const e of shape.enums) {
    lines.push(...renderEnum(e));
    lines.push("");
  }
  return lines.join("\n");
}

export function renderEnum(e: SdkEnum): string[] {
  const lines: string[] = [];
  lines.push(`class ${e.pyName}(str, Enum):`);
  lines.push(`    """${docstring(e.docstring ?? e.name)}"""`);
  for (const m of e.members) {
    lines.push(`    ${m.pyName} = "${m.value}"`);
  }
  return lines;
}

/* ─────────────────────────────  Top-level  ────────────────────────── */

export function buildTopInit(rendererId: string, shape: SdkShape): string {
  return [
    header(rendererId),
    `from ._client import ${shape.clientName}`,
    "from ._version import VERSION as __version__",
    "",
    `__all__ = ["${shape.clientName}", "__version__"]`,
    "",
  ].join("\n");
}

export function buildVersion(rendererId: string, shape: SdkShape): string {
  return `${header(rendererId)}\nVERSION = "${shape.version}"\n`;
}

export function buildOperationsInit(rendererId: string, opsClass: string): string {
  return `${header(rendererId)}\nfrom ._operations import ${opsClass}\n\n__all__ = ["${opsClass}"]\n`;
}

export function buildModelsInit(rendererId: string, shape: SdkShape): string {
  const lines: string[] = [header(rendererId)];
  if (shape.models.length) {
    lines.push(`from ._models import ${shape.models.map((m) => m.pyName).join(", ")}`);
  }
  if (shape.enums.length) {
    lines.push(`from ._enums import ${shape.enums.map((e) => e.pyName).join(", ")}`);
  }
  const all = [...shape.models.map((m) => m.pyName), ...shape.enums.map((e) => e.pyName)];
  lines.push("");
  if (all.length) {
    lines.push(`__all__ = [${all.map((n) => `"${n}"`).join(", ")}]`);
  } else {
    lines.push("__all__: list[str] = []");
  }
  lines.push("");
  return lines.join("\n");
}

export function buildPatch(): string {
  return [
    "# Customize generated code here.",
    "#",
    "# Anything added or modified here is preserved across regenerations.",
    "",
    "def patch_sdk() -> None:",
    "    pass",
    "",
  ].join("\n");
}
