import type { EmitContext } from "@typespec/compiler";
import type { HelloPythonEmitterOptions } from "../lib.js";
import type { SdkShape } from "../sdk-ir.js";
import { writeFiles } from "./files.js";
import type { OutputFile, Renderer } from "./types.js";

const HEADER = "# Generated by @typespec/hello-python-emitter [string renderer]. Do not edit by hand.\n";

function init(reexports: string[]): string {
  return [HEADER, ...reexports.map((r) => r + "\n"), ""].join("\n");
}

function buildOperationsFile(shape: SdkShape): string {
  const lines: string[] = [HEADER, "from typing import Any", ""];
  for (const op of shape.operations) {
    const params = op.parameters
      .map((p) => `${p.pyName}: ${p.pyType}${p.optional ? " | None = None" : ""}`)
      .join(", ");
    lines.push(`def ${op.pyName}(${params}) -> ${op.returnType}:`);
    lines.push(`    """Stub implementation of \`${op.name}\` (string renderer)."""`);
    lines.push(`    raise NotImplementedError("Operation '${op.name}' is not implemented yet")`);
    lines.push("");
  }
  return lines.join("\n");
}

function buildModelsFile(shape: SdkShape): string {
  const lines: string[] = [
    HEADER,
    "from dataclasses import dataclass",
    "from typing import Any, Optional",
    "",
  ];
  if (shape.models.length === 0) {
    lines.push("# (no user-defined models found)");
    lines.push("");
    return lines.join("\n");
  }
  for (const m of shape.models) {
    lines.push("@dataclass");
    lines.push(`class ${m.pyName}:`);
    if (m.properties.length === 0) {
      lines.push("    pass");
    } else {
      for (const p of m.properties) {
        const ann = p.optional ? `Optional[${p.pyType}] = None` : p.pyType;
        lines.push(`    ${p.pyName}: ${ann}`);
      }
    }
    lines.push("");
  }
  return lines.join("\n");
}

function buildClientFile(shape: SdkShape): string {
  const lines: string[] = [
    HEADER,
    "from .operations._operations import (",
    ...shape.operations.map((o) => `    ${o.pyName},`),
    ")",
    "",
    "",
    `class ${shape.clientName}:`,
    '    """Synthetic top-level client (string renderer)."""',
    "",
    "    def __init__(self, endpoint: str) -> None:",
    "        self._endpoint = endpoint",
    "",
  ];
  for (const op of shape.operations) {
    const selfParams = [
      "self",
      ...op.parameters.map(
        (p) => `${p.pyName}: ${p.pyType}${p.optional ? " | None = None" : ""}`,
      ),
    ];
    const callArgs = op.parameters.map((p) => p.pyName).join(", ");
    lines.push(`    def ${op.pyName}(${selfParams.join(", ")}) -> ${op.returnType}:`);
    lines.push(`        return ${op.pyName}(${callArgs})`);
    lines.push("");
  }
  return lines.join("\n");
}

function buildUtilsFile(): string {
  return [
    HEADER,
    "from typing import Any",
    "",
    "",
    "def to_dict(value: Any) -> dict:",
    '    """Best-effort serialization helper (string renderer placeholder)."""',
    "    if hasattr(value, '__dict__'):",
    "        return dict(value.__dict__)",
    "    return dict(value)",
    "",
  ].join("\n");
}

function buildAll(shape: SdkShape): OutputFile[] {
  const topInit = init([
    `from ._client import ${shape.clientName}`,
    "from ._version import VERSION as __version__",
  ]);
  const opsInit = init(shape.operations.map((o) => `from ._operations import ${o.pyName}`));
  const modelsInit =
    shape.models.length === 0
      ? init([])
      : init(shape.models.map((m) => `from ._models import ${m.pyName}`));
  const utilsInit = init(["from ._utils import to_dict"]);

  return [
    { path: "__init__.py", content: topInit },
    { path: "_version.py", content: `${HEADER}VERSION = "${shape.version}"\n` },
    { path: "_client.py", content: buildClientFile(shape) },
    { path: "py.typed", content: "" },
    { path: "operations/__init__.py", content: opsInit },
    { path: "operations/_operations.py", content: buildOperationsFile(shape) },
    { path: "models/__init__.py", content: modelsInit },
    { path: "models/_models.py", content: buildModelsFile(shape) },
    { path: "utils/__init__.py", content: utilsInit },
    { path: "utils/_utils.py", content: buildUtilsFile() },
  ];
}

export const stringRenderer: Renderer = {
  id: "string",
  description: "Pure template-literal strings written via compiler.emitFile. Zero rendering framework.",
  async emit(context: EmitContext<HelloPythonEmitterOptions>, shape, outputDir) {
    const files = buildAll(shape);
    await writeFiles(context.program, outputDir, files);
  },
};
