import type { EmitContext } from "@typespec/compiler";
import type { HelloPythonEmitterOptions } from "../lib.js";
import type { SdkShape } from "../sdk-ir.js";
import { writeFiles } from "./files.js";
import type { OutputFile, Renderer } from "./types.js";

/**
 * Tiny mustache-lite engine.
 *
 * Supports:
 *  - `{{var}}` / `{{a.b}}`                              context lookup
 *  - `{{#each items}} ... {{this.x}} ... {{/each}}`     repeat block (one level)
 *
 * Templates avoid nested `{{#each}}` blocks; pre-flatten lists in the
 * context preparer instead. Just enough to demonstrate the templating
 * sweet-spot without pulling in a real engine.
 */
type Ctx = Record<string, unknown>;

export function renderTemplate(tpl: string, ctx: Ctx): string {
  // each (non-nested)
  tpl = tpl.replace(/\{\{#each (\w+)\}\}([\s\S]*?)\{\{\/each\}\}/g, (_m, key, body) => {
    const arr = (ctx[key] as unknown[]) ?? [];
    return arr.map((item) => renderTemplate(body, { ...ctx, this: item })).join("");
  });
  // var
  tpl = tpl.replace(/\{\{([\w.]+)\}\}/g, (_m, path) => String(resolve(path, ctx) ?? ""));
  return tpl;
}

function resolve(path: string, ctx: Ctx): unknown {
  const parts = path.split(".");
  let cur: unknown = ctx;
  for (const p of parts) {
    if (cur == null) return undefined;
    cur = (cur as Record<string, unknown>)[p];
  }
  return cur;
}

const HEADER =
  "# Generated by @typespec/hello-python-emitter [template renderer]. Do not edit by hand.\n";

const OPS_TPL = `${HEADER}from typing import Any

{{#each operations}}
def {{this.pyName}}({{this.paramList}}) -> {{this.returnType}}:
    """Stub implementation of \`{{this.name}}\` (template renderer)."""
    raise NotImplementedError("Operation '{{this.name}}' is not implemented yet")

{{/each}}`;

const MODELS_TPL = `${HEADER}from dataclasses import dataclass
from typing import Any, Optional

{{#each models}}
@dataclass
class {{this.pyName}}:
{{this.body}}

{{/each}}`;

const CLIENT_TPL = `${HEADER}from .operations._operations import (
{{#each operations}}    {{this.pyName}},
{{/each}})


class {{clientName}}:
    """Synthetic top-level client (template renderer)."""

    def __init__(self, endpoint: str) -> None:
        self._endpoint = endpoint

{{#each operations}}    def {{this.pyName}}({{this.selfParamList}}) -> {{this.returnType}}:
        return {{this.pyName}}({{this.callArgs}})

{{/each}}`;

const UTILS_TPL = `${HEADER}from typing import Any


def to_dict(value: Any) -> dict:
    """Best-effort serialization helper (template renderer placeholder)."""
    if hasattr(value, "__dict__"):
        return dict(value.__dict__)
    return dict(value)
`;

const TOP_INIT_TPL = `${HEADER}from ._client import {{clientName}}
from ._version import VERSION as __version__
`;

const OPS_INIT_TPL = `${HEADER}{{#each operations}}from ._operations import {{this.pyName}}
{{/each}}`;

const MODELS_INIT_TPL = `${HEADER}{{#each models}}from ._models import {{this.pyName}}
{{/each}}`;

const UTILS_INIT_TPL = `${HEADER}from ._utils import to_dict
`;

const VERSION_TPL = `${HEADER}VERSION = "{{version}}"
`;

function prepareContext(shape: SdkShape): Ctx {
  return {
    clientName: shape.clientName,
    version: shape.version,
    operations: shape.operations.map((op) => ({
      name: op.name,
      pyName: op.pyName,
      returnType: op.returnType,
      paramList: op.parameters
        .map((p) => `${p.pyName}: ${p.pyType}${p.optional ? " | None = None" : ""}`)
        .join(", "),
      selfParamList: [
        "self",
        ...op.parameters.map(
          (p) => `${p.pyName}: ${p.pyType}${p.optional ? " | None = None" : ""}`,
        ),
      ].join(", "),
      callArgs: op.parameters.map((p) => p.pyName).join(", "),
    })),
    models: shape.models.map((m) => ({
      pyName: m.pyName,
      body:
        m.properties.length === 0
          ? "    pass"
          : m.properties
              .map(
                (p) =>
                  `    ${p.pyName}: ${p.optional ? `Optional[${p.pyType}] = None` : p.pyType}`,
              )
              .join("\n"),
    })),
  };
}

export const templateRenderer: Renderer = {
  id: "template",
  description: "Mustache-lite template engine (~25 LOC) filling Python template strings.",
  async emit(context: EmitContext<HelloPythonEmitterOptions>, shape, outputDir) {
    const ctx = prepareContext(shape);
    const files: OutputFile[] = [
      { path: "__init__.py", content: renderTemplate(TOP_INIT_TPL, ctx) },
      { path: "_version.py", content: renderTemplate(VERSION_TPL, ctx) },
      { path: "_client.py", content: renderTemplate(CLIENT_TPL, ctx) },
      { path: "py.typed", content: "" },
      { path: "operations/__init__.py", content: renderTemplate(OPS_INIT_TPL, ctx) },
      { path: "operations/_operations.py", content: renderTemplate(OPS_TPL, ctx) },
      { path: "models/__init__.py", content: renderTemplate(MODELS_INIT_TPL, ctx) },
      { path: "models/_models.py", content: renderTemplate(MODELS_TPL, ctx) },
      { path: "utils/__init__.py", content: renderTemplate(UTILS_INIT_TPL, ctx) },
      { path: "utils/_utils.py", content: renderTemplate(UTILS_TPL, ctx) },
    ];
    await writeFiles(context.program, outputDir, files);
  },
};
